import { Prescription } from '../Prescription';
import { genPrescriptionByMatrix } from '../PrescriptionsByMatrix';

describe('PrescriptionsByMatrix', () => {
  describe('genPrescriptionByMatrix', () => {
    it('should generate the prescription by matrix', () => {
      const prescriptions: Prescription[] = [
        {
          id: '1',
          programmingPlanId: '1',
          sampleMatrix: 'A',
          sampleStage: 'Avant récolte',
          region: '84',
          sampleCount: 1,
        },
        {
          id: '2',
          programmingPlanId: '1',
          sampleMatrix: 'A',
          sampleStage: 'Avant récolte',
          region: '53',
          sampleCount: 2,
        },
        {
          id: '3',
          programmingPlanId: '1',
          sampleMatrix: 'B',
          sampleStage: 'Avant récolte',
          region: '01',
          sampleCount: 3,
        },
        {
          id: '4',
          programmingPlanId: '1',
          sampleMatrix: 'A',
          sampleStage: 'Stockage',
          region: '94',
          sampleCount: 4,
        },
        {
          id: '5',
          programmingPlanId: '2',
          sampleMatrix: 'A',
          sampleStage: 'Avant récolte',
          region: '27',
          sampleCount: 5,
        },
      ];
      const result = genPrescriptionByMatrix(prescriptions);

      expect(result).toEqual([
        {
          programmingPlanId: '1',
          sampleMatrix: 'A',
          sampleStage: 'Avant récolte',
          regionalData: [
            { sampleCount: 1 },
            { sampleCount: 0 },
            { sampleCount: 2 },
            { sampleCount: 0 },
            { sampleCount: 0 },
            { sampleCount: 0 },
            { sampleCount: 0 },
            { sampleCount: 0 },
            { sampleCount: 0 },
            { sampleCount: 0 },
            { sampleCount: 0 },
            { sampleCount: 0 },
            { sampleCount: 0 },
            { sampleCount: 0 },
            { sampleCount: 0 },
            { sampleCount: 0 },
            { sampleCount: 0 },
            { sampleCount: 0 },
          ],
        },
        {
          programmingPlanId: '1',
          sampleMatrix: 'A',
          sampleStage: 'Stockage',
          regionalData: [
            { sampleCount: 0 },
            { sampleCount: 0 },
            { sampleCount: 0 },
            { sampleCount: 0 },
            { sampleCount: 4 },
            { sampleCount: 0 },
            { sampleCount: 0 },
            { sampleCount: 0 },
            { sampleCount: 0 },
            { sampleCount: 0 },
            { sampleCount: 0 },
            { sampleCount: 0 },
            { sampleCount: 0 },
            { sampleCount: 0 },
            { sampleCount: 0 },
            { sampleCount: 0 },
            { sampleCount: 0 },
            { sampleCount: 0 },
          ],
        },
        {
          programmingPlanId: '1',
          sampleMatrix: 'B',
          sampleStage: 'Avant récolte',
          regionalData: [
            { sampleCount: 0 },
            { sampleCount: 0 },
            { sampleCount: 0 },
            { sampleCount: 0 },
            { sampleCount: 0 },
            { sampleCount: 0 },
            { sampleCount: 0 },
            { sampleCount: 0 },
            { sampleCount: 0 },
            { sampleCount: 0 },
            { sampleCount: 0 },
            { sampleCount: 0 },
            { sampleCount: 0 },
            { sampleCount: 3 },
            { sampleCount: 0 },
            { sampleCount: 0 },
            { sampleCount: 0 },
            { sampleCount: 0 },
          ],
        },
        {
          programmingPlanId: '2',
          sampleMatrix: 'A',
          sampleStage: 'Avant récolte',
          regionalData: [
            { sampleCount: 0 },
            { sampleCount: 5 },
            { sampleCount: 0 },
            { sampleCount: 0 },
            { sampleCount: 0 },
            { sampleCount: 0 },
            { sampleCount: 0 },
            { sampleCount: 0 },
            { sampleCount: 0 },
            { sampleCount: 0 },
            { sampleCount: 0 },
            { sampleCount: 0 },
            { sampleCount: 0 },
            { sampleCount: 0 },
            { sampleCount: 0 },
            { sampleCount: 0 },
            { sampleCount: 0 },
            { sampleCount: 0 },
          ],
        },
      ]);
    });
  });
});
