#s3cmd --host http://localhost:9090 ls s3://maestro --no-ssl
services:
  s3mock:
    image: adobe/s3mock:latest
    container_name: maestro_s3
    environment:
      - debug=true
      - retainFilesOnExit=true
      - root=containers3root
      - initialBuckets=maestro
    ports:
      - 9090:9090
    volumes:
      - ./locals3root:/containers3root
  s3manager:
    image: cloudlena/s3manager
    container_name: maestro_s3manager
    ports:
      - 8081:8080
    environment:
      - ENDPOINT=s3mock:9090
      - ACCESS_KEY_ID=foo
      - SECRET_ACCESS_KEY=bar
      - USE_SSL=false
      - SKIP_SSL_VERIFICATION=true
      - REGION=us-east-1
    depends_on:
      - s3mock
  browserless:
    image: ghcr.io/browserless/chromium
    container_name: maestro_browserless
    network_mode: 'host'
    environment:
      - TOKEN=1234512345
      - CONCURRENT=1
      - PORT=3002
  maildev:
    image: soulteary/maildev
    container_name: maestro_maildev
    ports:
      - 1025:1025
      - 1080:1080
  oidc:
    image: ghcr.io/dexidp/dex:latest
    container_name: maestro_oidc
    command: dex serve /etc/dex/config.yaml
    ports:
      - 5556:5556
    volumes:
      - ./dex/config.yaml:/etc/dex/config.yaml:ro
  db:
    image: postgis/postgis:17-3.5
    container_name: maestro_db
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=200
    environment:
      - PGUSER=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=maestro
    ports:
      - 5432:5432
