services:
  caddy:
    image: caddy:2-alpine
    container_name: maestro_caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - dex

  dex:
    image: ghcr.io/dexidp/dex:latest
    container_name: maestro_dex
    restart: unless-stopped
    command: dex serve /etc/dex/config.yaml
    expose:
      - "5556"
    volumes:
      - ./dex-config.yaml:/etc/dex/config.yaml:ro
  browserless:
    image: ghcr.io/browserless/chromium
    container_name: maestro_browserless
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
#      TODO à modifier
      - TOKEN=1234512345
      - CONCURRENT=1
      - PORT=3002

volumes:
  caddy_data:
  caddy_config:
