import { z } from 'zod';

export const UserPermission = z.enum([
  'administrationMaestro',
  'manageMascarade',
  'manageNotices',
  'manageSpecificDataFields',
  'manageLaboratoryConfig',
  'manageUsers',
  'createSample',
  'readSamples',
  'updateSample',
  'deleteSample',
  'exportSamplesWithCodes',
  'downloadSupportDocument',
  'downloadAnalysisRequestDocument',
  'manageProgrammingPlan',
  'manageProgrammingPlanSettings',
  'approveProgrammingPlan',
  'validateProgrammingPlan',
  'closeProgrammingPlan',
  'viewProgrammingPlans',
  'readProgrammingPlansInProgress',
  'readProgrammingPlanSubmittedToRegion',
  'readProgrammingPlanApprovedByRegion',
  'readProgrammingPlanSubmittedToDepartments',
  'readProgrammingPlanValidated',
  'readProgrammingPlanClosed',
  'createPrescription',
  'readPrescriptions',
  'updatePrescription',
  'updatePrescriptionLaboratories',
  'deletePrescription',
  'commentPrescription',
  'distributePrescriptionToDepartments',
  'distributePrescriptionToSlaughterhouses',
  'createResource',
  'readDocuments',
  'deleteDocument',
  'deleteSampleDocument',
  'readCompanies',
  'performAnalysis',
  'readAnalysis',
  'viewDashboard',
  'readLaboratoryCompetences',
  'manageLaboratoryCompetences',
  'manageLaboratoryAgreements'
]);

export type UserPermission = z.infer<typeof UserPermission>;
