import { z } from 'zod';

export const UserPermission = z.enum([
  'administrationMaestro',
  'createSample',
  'readSamples',
  'updateSample',
  'deleteSample',
  'downloadSupportDocument',
  'downloadAnalysisRequestDocument',
  'manageProgrammingPlan',
  'approveProgrammingPlan',
  'validateProgrammingPlan',
  'closeProgrammingPlan',
  'readProgrammingPlans',
  'readProgrammingPlansInProgress',
  'readProgrammingPlanSubmittedToRegion',
  'readProgrammingPlanApprovedByRegion',
  'readProgrammingPlanSubmittedToDepartments',
  'readProgrammingPlanValidated',
  'readProgrammingPlanClosed',
  'createPrescription',
  'readPrescriptions',
  'updatePrescription',
  'updatePrescriptionLaboratories',
  'deletePrescription',
  'commentPrescription',
  'distributePrescriptionToDepartments',
  'distributePrescriptionToSlaughterhouses',
  'createResource',
  'readDocuments',
  'deleteDocument',
  'deleteSampleDocument',
  'readCompanies',
  'createAnalysis',
  'readAnalysis',
  'viewDashboard',
  'readLaboratoryCompetences',
  'manageLaboratoryCompetences'
]);

export type UserPermission = z.infer<typeof UserPermission>;
