import { SSD2Id } from 'maestro-shared/referential/Residue/SSD2Id';

export const inovalysReferential: Record<string, SSD2Id> = {
  'DDD 4,4 (p,p\')': 'RF-0119-004-PPP',
  'DDE 4,4 (p,p\')': 'RF-0119-002-PPP',
  'DDT 2,4 (o,p\')': 'RF-0119-003-PPP',
  'DDT 4,4 (p,p\')': 'RF-0119-006-PPP',
  'Dicofol  (o,p\')': 'RF-0130-003-PPP',
  'Dicofol (p,p\')': 'RF-0130-002-PPP',
  '4-Bromophénylurée': 'RF-00003387-PAR',
  '8,9-Z-Avermectine B1a': 'RF-0011-002-PPP',
  'Abamectine (B1a + B1b + 8,9-Z)': 'RF-00004655-PAR',
  'Aldicarbe (+ sulfone + sulfoxyde)': 'RF-0020-001-PPP',
  'Avermectine B1a': 'RF-0011-003-PPP',
  'Avermectine B1b': 'RF-0011-004-PPP',
  'Benfuracarb': 'RF-0040-001-PPP',
  'BTS 44595 (métabolite du prochloraz)': 'RF-00003328-PAR',
  'BTS 44596 (métabolite du prochloraz)': 'RF-00003329-PAR',
  'Bénomyl': 'RF-0041-003-PPP',
  'Captane (+ THPI)': 'RF-00004681-PAR',
  'Carbendazim (+ bénomyl)': 'RF-0041-001-PPP',
  'Carbofurane (+ carbofurane-OH)': 'RF-00003374-PAR',
  'Carbofurane': 'RF-0065-003-PPP',
  'Carbofurane-3-hydroxy': 'RF-0065-002-PPP',
  'Carbosulfane': 'RF-0068-001-PPP',
  'Carboxine (+ sulfone + sulfoxyde)': 'RF-00011559-PAR',
  'Carboxine sulfone': 'RF-0069-001-PPP',
  'Carboxine sulfoxyde': 'RF-00005982-PAR',
  'Clethodim (+ Séthoxydim)': 'RF-0096-001-PPP',
  'DDT(DDT 4,4 + DDT 2,4 + DDE 4,4 + DDD 4,4)': 'RF-0119-001-PPP',
  'Diclofop (+ diclofop méthyl)': 'RF-00012875-PAR',
  'Dicofol (p,p´ + o,p´)': 'RF-0130-001-PPP',
  'Dieldrine (+ aldrine)': 'RF-0021-001-PPP',
  'Disulfoton (+ sulfone + sulfoxide)': 'RF-0149-001-PPP',
  'Déméton-S-méthyl sulfone': 'RF-0323-003-PPP',
  'Endosulfan (alpha + bêta + endosulfan)': 'RF-0155-001-PPP',
  'Fenamiphos (+ sulfone + sulfoxide)': 'RF-0173-001-PPP',
  'Fenamiphos sulfone': 'RF-0173-003-PPP',
  'Fenamiphos sulfoxide': 'RF-0173-002-PPP',
  'Fenchlorphos (+ oxon)': 'RF-0178-001-PPP',
  'Fenchlorphos oxon': 'RF-0178-003-PPP',
  'Fenthion (+ sulf + sulfox + oxon + oxon-sulf + oxon-sulfox)': 'RF-0187-001-PPP',
  'Fenvalérate (somme des isomères + esfenvalerate)': 'RF-0690-006-PPP',
  'Fipronil (+ sulfone)': 'RF-0192-001-PPP',
  'Flonicamide (+ TFNA + TFNG)': 'RF-00004683-PAR',
  'Folpel (+ phtalimide)': 'RF-00004687-PAR',
  'Fosetyl (+ ac. phosphoreux)': 'RF-0225-001-PPP',
  'Furathiocarb': 'RF-0228-001-PPP',
  'Halauxifen méthyl (+ halauxifen)': 'RF-00004666-PAR',
  'Halauxifen méthyl': 'RF-00007584-PAR',
  'Halauxifen': 'RF-00004665-PAR',
  'Heptachlore (+ heptachlore epoxide)': 'RF-0236-001-PPP',
  'Malathion (+ malaoxon)': 'RF-0266-001-PPP',
  'MCPA (L)': 'RF-0271-005-PPP',
  'MCPA+MCPB (L)': 'RF-0271-004-PPP',
  'MCPB (L)': 'RF-0271-002-PPP',
  'Méfentrifluconazole': 'RF-00009360-PAR',
  'Méthiocarb (+ sulfone + sulfoxide)': 'RF-0291-001-PPP',
  'Méthiocarb sulfone': 'RF-0291-004-PPP',
  'Méthiocarb sulfoxide': 'RF-0291-003-PPP',
  'Méthiocarb': 'RF-0291-002-PPP',
  'Métobromuron (+4-Bromophénylurée)': 'RF-00014532-PAR',
  'Oxydéméton méthyl (+ déméton-S-méthyl sulf.)': 'RF-0323-001-PPP',
  'Oxydéméton méthyl': 'RF-0323-004-PPP',
  'Parathion méthyl (+ paraoxon méthyl)': 'RF-0328-001-PPP',
  'Phorate (+ oxon + sulfone + sulfoxide)': 'RF-0336-001-PPP',
  'Phosmet (+ phosmet oxon)': 'RF-0338-001-PPP',
  'Pirimicarbe (+ desméthyl)': 'RF-0347-001-PPP',
  'Prochloraz (+ BTS 44595 + BTS 44596)': 'RF-00012032-PAR',
  'Prothioconazole : prothioconazole-desthio (somme des isomères)': 'RF-0868-001-PPP',
  'Quintozène (+ pentachloroaniline)': 'RF-0383-001-PPP',
  'Spinetoram (J+L)': 'RF-00013247-PAR',
  'Spirotétramat (+ enol)': 'RF-00000030-PAR',
  'Séthoxydim': 'RF-0096-003-PPP',
  'TFNA': 'RF-00003348-PAR',
  'TFNG': 'RF-00003349-PAR',
  'Tolylfluanide (+ DMST)': 'RF-0425-001-PPP',
  '2,4,5-T (L)': 'RF-00003041-PAR',
  '2,4-D (L)': 'RF-0010-003-PPP',
  '2,4-DB (L)': 'RF-00004646-PAR',
  '2-Phénylphénol (L)': 'RF-0823-001-PPP',
  'Acétamipride': 'RF-0014-001-PPP',
  'Atrazine-2-hydroxy': 'RF-0477-001-PPP',
  'Azadirachtine': 'RF-0030-001-PPP',
  'Bénalaxil (dont bénalaxil-M, somme des isomères)': 'RF-0038-001-PPP',
  'Benflubutamid': 'RF-0037-001-PPP',
  'Bentazone (L)': 'RF-0042-002-PPP',
  'Bifenazate (L)': 'RF-0044-001-PPP',
  'Bifenthrine (somme des isomères)': 'RF-0046-001-PPP',
  'Bitertanol (somme des isomères)': 'RF-0048-001-PPP',
  'Bromoxynil (+ sels)': 'RF-00003327-PAR',
  'Bromuconazole (somme de diastéroisomers)': 'RF-0054-001-PPP',
  'Carbetamide (somme des isomères)': 'RF-00012044-PAR',
  'Carbophénothion': 'RF-0535-001-PPP',
  'Carfentrazone éthyl (L)': '',
  'Chloridazon (L)': '',
  'Chlorophacinone': '',
  'Desméthyl chlorpyriphos méthyl': '',
  'Cinidon éthyl (somme des isomères)': '',
  'Clodinafop (+ isomères + sels)': '',
  'Cycloxydime (L)': '',
  'Cyflufénamid (somme des isomères)': '',
  'Cyfluthrine (somme des isomères)': '',
  'Cyhalofop butyl': '',
  'Cyperméthrine (somme des isomères)': '',
  'Déméton-S-méthyl': '',
  'Dichlofluanide': '',
  'Dichlorprop (L)': '',
  '2,6-Difluorobenzamide (métabolite du diflubenzuron)': '',
  'Diflufénican': '',
  'Diméthénamide (somme des isomères)': '',
  'Diméthomorph (sommes des isomères)': '',
  'Diniconazole (somme des isomères)': '',
  'Dinocap (L)': '',
  'DCPMU (métabolite du diuron)': '',
  'DCPU (métabolite du diuron)': '',
  'DMPF (N-2,4-Diméthylphényl-N\'-méthylformamidine)': '',
'Emamectine benzoate (B1b)': '',
  'Emamectine benzoate B1a (+sels)': '',
  'Fénobucarb': '',
  'Fénoprop (2,4,5-TP)': '',
  'Fénoxaprop-P-ethyl': '',
  'Fenpropidine (+ sels)': '',
  'Fenpropimorphe (somme des isomères)': '',
  'Fensulfothion oxon sulfone': '',
  'Fensulfothion sulfone': '',
  'Fipronil désulfinyl': '',
  'Fipronil sulfide': '',
  'TFNA-AM': '',
  'Fluazifop-P (L)': '',
  'Flufénacet (L)': '',
  'Fluoxastrobine (somme des isomères)': '',
  'Fluroxypyr (L)': '',
  'Haloxyfop (L)': '',
  'Haloxyfop méthyl': '',
  'HCH (alpha)': '',
  'HCH (bêta)': '',
  'Imazamox (+ sels)': '',
  'Indoxacarb (+ énantiomères)': '',
  'Iodosulfuron-methyl  (+ sels)': '',
  'Ioxynil': '',
  'Isofenphos éthyl': '',
  'Isofenphos méthyl': '',
  'IPPMU (métabolite isoproturon)': '',
  'IPPU (métabolite isoproturon)': '',
  'Isoxaflutole (L)': '',
  'Lindane (=HCH gamma)': '',
  'Lufénuron (Somme des isomères)': '',
  'Mécoprop (dont mécoprop-p)': '',
  'Méptyldinocap (L)': '',
  'Métaflumizone (somme des isomères)': '',
  'Métalaxyl + métalaxyl-M (somme d\'isomères)': '',
'Métazachlor (L)': '',
  'Metconazole (somme d\'isomères)': '',
'Méthabenzthiazuron': '',
  'Méthomyl': '',
  'Méthoxychlore': '',
  'Méthoxyfenozide': '',
  'Desméthyl métobromuron': '',
  'Métolachlore + S-metolachlor (somme des isomères)': '',
  'Métrafenone': '',
  'Mevinphos (somme des isomères)': '',
  'Napropamide (somme des isomères)': '',
  'Oxathiapiproline': '',
  'Pencycuron (L)': '',
  'Pendiméthaline': '',
  'Perméthrine (somme des isomères)': '',
  'Pirimiphos éthyl': '',
  'Propamocarb (+ sels)': '',
  'Propiconazole (sommes des isomères)': '',
  'Propoxycarbazone (L)': '',
  'Pydiflumétofen': '',
  'Pyréthrines': '',
  'Pyridate (L)': '',
  'Pyriofénone': '',
  'Resméthrine (somme des isomères)': '',
  'Sedaxane (somme des isomères)': '',
  'Spinosad (A + D)': '',
  'Spiromésifen': '',
  'Spirotétramat-BYI08330-enol-glucoside': '',
  'Spirotétramat-BYI08330-ketohydroxy': '',
  'Spirotétramat-BYI08330-monohydroxy': '',
  'Spiroxamine (sommes des isomères)': '',
  'CMBA (métabolite sulcotrione)': '',
  'Sulfoxaflor (somme des isomères)': '',
  'Tau fluvalinate': '',
  'Tébufenpyrade': '',
  'Tecnazène': '',
  'Tépraloxydim (L)': '',
  'Térbufos': '',
  'Térbufos sulfone': '',
  'Térbufos sulfoxide': '',
  'Terbuthylazine deséthyl': '',
  'Tétradifon': '',
  'Triadiménol (somme des isomères)': '',
  'Tridémorphe': '',
  'Triflumizole (L)': '',
  'Trinexapac (+sels)': '',
  'Dithiocarbamates (dosage global exprimé en CS2)': '',

};
