/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import { ColumnType, type Kysely } from 'kysely';
import { type Region } from 'maestro-shared/referential/Region';
import { AnalysisMethod } from 'maestro-shared/schema/Analysis/AnalysisMethod';
import { AnalysisStatus } from 'maestro-shared/schema/Analysis/AnalysisStatus';
import { ResidueCompliance } from 'maestro-shared/schema/Analysis/Residue/ResidueCompliance';
import { type DocumentKind } from 'maestro-shared/schema/Document/DocumentKind';
import { UserRole } from 'maestro-shared/schema/User/UserRole';
import { SSD2Id } from 'maestro-shared/referential/Residue/SSD2Id';
import { PartialResidue } from 'maestro-shared/schema/Analysis/Residue/Residue';
import { ResultKind } from 'maestro-shared/schema/Analysis/Residue/ResultKind';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Point = {
  x: number;
  y: number;
};

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface _MatrixReferential {
  code: string | null;
  label: string | null;
}

export interface _Referential {
  code: string | null;
  label: string | null;
}

export interface Analysis {
  compliance: boolean | null;
  createdAt: Generated<Timestamp | null>;
  createdBy: string | null;
  id: Generated<string>;
  notesOnCompliance: string | null;
  reportDocumentId: string | null;
  sampleId: string | null;
  status: AnalysisStatus;
}

export interface AnalysisResidues {
  analysisId: string;
  analysisMethod: AnalysisMethod;
  compliance: ResidueCompliance | null;
  lmr: number | null;
  notesOnPollutionRisk: string | null;
  notesOnResult: string | null;
  pollutionRisk: string | null;
  reference: SSD2Id | null;
  residueNumber: number;
  result: number | null;
  resultHigherThanArfd: string | null;
  resultKind: ResultKind | null;
  substanceApproved: string | null;
  substanceAuthorised: string | null;
}

export interface AnalysisErrors {
  analysisId: string;
  residues: {
    old: Omit<PartialResidue, 'analysisId'>[];
    new: Omit<PartialResidue, 'analysisId'>[];
  };
}

export interface AnalysisResiduesTmp {
  analysisId: string | null;
  compliance: string | null;
  kind: string | null;
  lmr: number | null;
  notesOnPollutionRisk: string | null;
  notesOnResult: string | null;
  originalName: string | null;
  pollutionRisk: string | null;
  reference: string | null;
  residueNumber: number | null;
  result: number | null;
  resultHigherThanArfd: string | null;
  resultKind: string | null;
  substanceApproved: string | null;
  substanceAuthorised: string | null;
}

export interface Companies {
  address: string | null;
  city: string | null;
  nafCode: string | null;
  name: string;
  postalCode: string | null;
  siret: string;
  tradeName: string | null;
}

export interface Documents {
  createdAt: Generated<Timestamp | null>;
  createdBy: string | null;
  filename: string;
  id: Generated<string>;
  kind: DocumentKind;
}

export interface KnexMigrations {
  batch: number | null;
  id: Generated<number>;
  migrationTime: Timestamp | null;
  name: string | null;
}

export interface KnexMigrationsLock {
  index: Generated<number>;
  isLocked: number | null;
}

export interface Laboratories {
  email: string;
  id: Generated<string>;
  name: string;
}

export interface Prescriptions {
  context: string | null;
  id: Generated<string>;
  matrix: string | null;
  notes: string | null;
  programmingPlanId: string | null;
  stages: string[] | null;
}

export interface PrescriptionSubstances {
  analysisMethod: string;
  prescriptionId: string;
  substanceCode: string;
}

export interface ProgrammingPlans {
  createdAt: Generated<Timestamp | null>;
  createdBy: string | null;
  id: Generated<string>;
  status: string;
  statusDrom: string | null;
  year: number;
}

export interface RegionalPrescriptionComments {
  comment: string;
  createdAt: Generated<Timestamp | null>;
  createdBy: string;
  id: Generated<string>;
  prescriptionId: string;
  region: string;
}

export interface RegionalPrescriptions {
  laboratoryId: string | null;
  prescriptionId: string;
  region: string;
  sampleCount: number | null;
}

export interface ResidueAnalytes {
  analysisId: string;
  analyteNumber: number;
  reference: SSD2Id | null;
  residueNumber: number;
  result: number | null;
  resultKind: string | null;
}

export interface SampleItems {
  compliance200263: boolean | null;
  itemNumber: number;
  ownerEmail: string | null;
  ownerFirstName: string | null;
  ownerLastName: string | null;
  quantity: number | null;
  quantityUnit: string | null;
  recipientKind: string | null;
  sampleId: string;
  sealId: string | null;
  supportDocumentId: string | null;
}

export interface Samples {
  companyOffline: string | null;
  companySiret: string | null;
  context: string;
  createdAt: Generated<Timestamp | null>;
  cultureKind: string | null;
  department: string | null;
  geolocation: Point | null;
  id: Generated<string>;
  laboratoryId: string | null;
  lastUpdatedAt: Generated<Timestamp | null>;
  legalContext: string;
  matrix: string | null;
  matrixDetails: string | null;
  matrixPart: string | null;
  notesOnAdmissibility: string | null;
  notesOnCreation: string | null;
  notesOnItems: string | null;
  notesOnMatrix: string | null;
  parcel: string | null;
  prescriptionId: string | null;
  programmingPlanId: string | null;
  receivedAt: Timestamp | null;
  reference: string;
  region: string;
  releaseControl: boolean | null;
  resytalId: string | null;
  sampledAt: Timestamp;
  sampledBy: string | null;
  sentAt: Timestamp | null;
  stage: string | null;
  status: string;
}

export interface SampleSequenceNumbers {
  nextSequence: Generated<number>;
  programmingPlanYear: number;
  region: string;
}

export interface Substances {
  code: string;
  label: string;
}

export interface Users {
  email: string;
  firstName: string;
  id: Generated<string>;
  lastName: string;
  region: Region | null;
  role: UserRole;
  loggedSecrets: ColumnType<string[], string[] | null, string[]>
}

export interface SampleDocuments {
  documentId: string;
  sampleId: string;
}

export interface DB {
  _MatrixReferential: _MatrixReferential;
  _Referential: _Referential;
  analysis: Analysis;
  analysisResidues: AnalysisResidues;
  analysisErrors: AnalysisErrors;
  analysisResiduesTmp: AnalysisResiduesTmp;
  companies: Companies;
  documents: Documents;
  knexMigrations: KnexMigrations;
  knexMigrationsLock: KnexMigrationsLock;
  laboratories: Laboratories;
  prescriptions: Prescriptions;
  prescriptionSubstances: PrescriptionSubstances;
  programmingPlans: ProgrammingPlans;
  regionalPrescriptionComments: RegionalPrescriptionComments;
  regionalPrescriptions: RegionalPrescriptions;
  residueAnalytes: ResidueAnalytes;
  sampleDocuments: SampleDocuments;
  sampleItems: SampleItems;
  samples: Samples;
  sampleSequenceNumbers: SampleSequenceNumbers;
  substances: Substances;
  users: Users;
}
export type KyselyMaestro = Kysely<DB>;
