/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import { ColumnType, Expression, type Kysely, sql } from 'kysely';
import { Department } from 'maestro-shared/referential/Department';
import { LaboratoryShortName } from 'maestro-shared/referential/Laboratory';
import { LegalContext } from 'maestro-shared/referential/LegalContext';
import { type Region } from 'maestro-shared/referential/Region';
import { SSD2Id } from 'maestro-shared/referential/Residue/SSD2Id';
import { Stage } from 'maestro-shared/referential/Stage';
import { AnalysisMethod } from 'maestro-shared/schema/Analysis/AnalysisMethod';
import { AnalysisStatus } from 'maestro-shared/schema/Analysis/AnalysisStatus';
import { PartialResidue } from 'maestro-shared/schema/Analysis/Residue/Residue';
import { ResidueCompliance } from 'maestro-shared/schema/Analysis/Residue/ResidueCompliance';
import { ResultKind } from 'maestro-shared/schema/Analysis/Residue/ResultKind';
import { CompanyKind } from 'maestro-shared/schema/Company/CompanyKind';
import { type DocumentKind } from 'maestro-shared/schema/Document/DocumentKind';
import { LaboratoryAnalyticalMethod } from 'maestro-shared/schema/Laboratory/LaboratoryAnalyticalMethod';
import { LaboratoryValidationMethod } from 'maestro-shared/schema/Laboratory/LaboratoryValidationMethod';
import { Context } from 'maestro-shared/schema/ProgrammingPlan/Context';
import { DistributionKind } from 'maestro-shared/schema/ProgrammingPlan/DistributionKind';
import { ProgrammingPlanDomain } from 'maestro-shared/schema/ProgrammingPlan/ProgrammingPlanDomain';
import { ProgrammingPlanKind } from 'maestro-shared/schema/ProgrammingPlan/ProgrammingPlanKind';
import {
  CommemoratifSigle,
  CommemoratifValueSigle,
  SachaCommemoratifTypeDonnee
} from 'maestro-shared/schema/SachaCommemoratif/SachaCommemoratif';
import { SampleItemRecipientKind } from 'maestro-shared/schema/Sample/SampleItemRecipientKind';
import { SampleMatrixSpecificData } from 'maestro-shared/schema/Sample/SampleMatrixSpecificData';
import { SubstanceKind } from 'maestro-shared/schema/Substance/SubstanceKind';
import { UserRole } from 'maestro-shared/schema/User/UserRole';
import { MaestroDate } from 'maestro-shared/utils/date';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Point = {
  x: number;
  y: number;
};

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Analysis {
  compliance: boolean | null;
  createdAt: Generated<Timestamp | null>;
  emailReceivedAt: Timestamp | null;
  createdBy: string | null;
  id: Generated<string>;
  notesOnCompliance: string | null;
  sampleId: string | null;
  status: AnalysisStatus;
}

export interface AnalysisReportDocuments {
  analysisId: string;
  documentId: string;
}

export interface AnalysisResidues {
  analysisId: string;
  analysisMethod: AnalysisMethod;
  compliance: ResidueCompliance | null;
  lmr: number | null;
  notesOnPollutionRisk: string | null;
  notesOnResult: string | null;
  pollutionRisk: string | null;
  reference: SSD2Id | null;
  residueNumber: number;
  result: number | null;
  resultHigherThanArfd: string | null;
  resultKind: ColumnType<ResultKind, ResultKind | 'ND', ResultKind | 'ND'>;
  substanceApproved: string | null;
  substanceAuthorised: string | null;
  unknownLabel: string | null;
  analysisDate: MaestroDate | null;
}

export interface AnalysisErrors {
  analysisId: string;
  residues: {
    old: Omit<PartialResidue, 'analysisId'>[];
    new: Omit<PartialResidue, 'analysisId'>[];
  };
}

export interface Companies {
  address: string | null;
  city: string | null;
  nafCode: string | null;
  name: string;
  postalCode: string | null;
  siret: string;
  tradeName: string | null;
  kinds: CompanyKind[];
  geolocation: Point | null;
}

export interface Documents {
  createdAt: Generated<Timestamp | null>;
  createdBy: string | null;
  filename: string;
  id: Generated<string>;
  kind: DocumentKind;
}

export interface KnexMigrations {
  batch: number | null;
  id: Generated<number>;
  migrationTime: Timestamp | null;
  name: string | null;
}

export interface SachaSender {
  sachaSigle: string;
  name: string;
  sachaEmail: string;
}

export interface SachaResidueMappings {
  label: string;
  ssd2Id: string;
}

export interface SachaConf {
  versionReferenceStandardisees: string;
  versionReferencePrescripteur: string;
}

export interface SachaCommemoratifs {
  sigle: CommemoratifSigle;
  libelle: string;
  typeDonnee: SachaCommemoratifTypeDonnee;
  unite: string | null;
}

export interface SachaCommemoratifValues {
  sigle: CommemoratifValueSigle;
  commemoratifSigle: CommemoratifSigle;
  libelle: string;
}

export interface Laboratories {
  emails: string[];
  id: Generated<string>;
  shortName: LaboratoryShortName;
  name: string;
  address: string;
  postalCode: string;
  city: string;
  emailsAnalysisResult: string[];
  sachaEmail: string | null;
  sachaGpgPublicKey: string | null;
  sachaSigle: string | null;
}

export interface LaboratoryResidueMapping {
  laboratoryId: string;
  label: string;
  ssd2Id: SSD2Id | null;
}

export interface LaboratoryAgreements {
  laboratoryId: string;
  programmingPlanId: string;
  substanceKind: SubstanceKind;
}

export interface LaboratoryAnalyticalCompetences {
  id: Generated<string>;
  laboratoryId: string;
  residueReference: SSD2Id;
  analyteReference: SSD2Id | null;
  analyticalMethod: LaboratoryAnalyticalMethod | null;
  validationMethod: LaboratoryValidationMethod | null;
  analysisMethod: AnalysisMethod | null;
  isCompleteDefinitionAnalysis: boolean | null;
  detectionLimit: number | null;
  quantificationLimit: number | null;
}

export interface Notices {
  type: 'root' | 'dashboard';
  title: string | null;
  description: string | null;
}

export interface Prescriptions {
  context: string | null;
  id: Generated<string>;
  matrix: string | null;
  notes: string | null;
  programmingPlanId: string | null;
  stages: string[] | null;
}

export interface PrescriptionSubstances {
  analysisMethod: string;
  prescriptionId: string;
  substance: string;
}

export interface ProgrammingPlans {
  createdAt: Generated<Timestamp | null>;
  createdBy: string | null;
  id: Generated<string>;
  status: string;
  statusDrom: string | null;
  year: number;
  domain: ProgrammingPlanDomain;
  kinds: ProgrammingPlanKind[];
  contexts: Context[];
  legalContexts: LegalContext[];
  samplesOutsidePlanAllowed: boolean;
  title: string;
  substanceKinds: SubstanceKind[];
  distributionKind: DistributionKind;
  closedAt: Timestamp | null;
  closedBy: string | null;
}

export interface LocalPrescriptionComments {
  comment: string;
  createdAt: Generated<Timestamp | null>;
  createdBy: string;
  id: Generated<string>;
  prescriptionId: string;
  region: string;
}

export interface LocalPrescriptions {
  laboratoryId: string | null;
  prescriptionId: string;
  region: string;
  sampleCount: number | null;
}

export interface SampleSpecificDataAttributes {
  attribute: string;
  sachaCommemoratifSigle: CommemoratifSigle | null;
  inDai: boolean;
}

export interface SampleSpecificDataAttributeValues {
  attribute: string;
  attributeValue: string;
  sachaCommemoratifValueSigle: CommemoratifValueSigle;
}

export interface ResidueAnalytes {
  analysisId: string;
  analyteNumber: number;
  reference: SSD2Id | null;
  residueNumber: number;
  result: number | null;
  resultKind: ColumnType<
    ResultKind,
    ResultKind | 'ND',
    ResultKind | 'ND'
  > | null;
}

export interface SampleItems {
  compliance200263: boolean | null;
  itemNumber: number;
  copyNumber: number;
  ownerEmail: string | null;
  ownerFirstName: string | null;
  ownerLastName: string | null;
  quantity: number | null;
  quantityUnit: string | null;
  recipientKind: SampleItemRecipientKind | null;
  sampleId: string;
  sealId: string | null;
  supportDocumentId: string | null;
  laboratoryId: string | null;
}

export interface Samples {
  companyOffline: string | null;
  companySiret: string | null;
  context: string;
  createdAt: Generated<Timestamp | null>;
  department: string | null;
  geolocation: Point | null;
  id: Generated<string>;
  laboratoryId: string | null;
  lastUpdatedAt: Generated<Timestamp | null>;
  legalContext: string;
  matrix: string | null;
  notesOnAdmissibility: string | null;
  notesOnCreation: string | null;
  notesOnItems: string | null;
  notesOnMatrix: string | null;
  parcel: string | null;
  prescriptionId: string | null;
  programmingPlanId: string | null;
  receivedAt: Timestamp | null;
  reference: string;
  region: string;
  resytalId: string | null;
  sampledAt: Timestamp;
  sampledBy: string | null;
  sentAt: Timestamp | null;
  specificData: SampleMatrixSpecificData;
  stage: Stage | null;
  status: string;
}

export interface SampleSequenceNumbers {
  nextSequence: Generated<number>;
  programmingPlanYear: number;
  region: string;
}

export interface Users {
  email: string;
  name: string | null;
  id: Generated<string>;
  region: Region | null;
  department: Department | null;
  roles: UserRole[];
  loggedSecrets: ColumnType<string[], string[] | null, string[]>;
  programmingPlanKinds: ProgrammingPlanKind[];
  laboratoryId: string | null;
  disabled: boolean;
}

export interface UserCompanies {
  companySiret: string;
  userId: string;
}

export interface SampleDocuments {
  documentId: string;
  sampleId: string;
}

export interface Departments {
  id: string;
  geometry: ColumnType<never, unknown, unknown>;
}

export interface DB {
  analysis: Analysis;
  analysisReportDocuments: AnalysisReportDocuments;
  analysisResidues: AnalysisResidues;
  analysisErrors: AnalysisErrors;
  companies: Companies;
  departments: Departments;
  documents: Documents;
  knexMigrations: KnexMigrations;
  laboratories: Laboratories;
  laboratoryResidueMappings: LaboratoryResidueMapping;
  laboratoryAgreements: LaboratoryAgreements;
  notices: Notices;
  prescriptions: Prescriptions;
  prescriptionSubstances: PrescriptionSubstances;
  programmingPlans: ProgrammingPlans;
  sampleSpecificDataAttributes: SampleSpecificDataAttributes;
  sampleSpecificDataAttributeValues: SampleSpecificDataAttributeValues;
  localPrescriptionComments: LocalPrescriptionComments;
  localPrescriptions: LocalPrescriptions;
  residueAnalytes: ResidueAnalytes;
  sachaResidueMappings: SachaResidueMappings;
  sachaConf: SachaConf;
  sachaCommemoratifs: SachaCommemoratifs;
  sachaCommemoratifValues: SachaCommemoratifValues;
  sachaSender: SachaSender;
  sampleDocuments: SampleDocuments;
  sampleItems: SampleItems;
  samples: Samples;
  sampleSequenceNumbers: SampleSequenceNumbers;
  users: Users;
  userCompanies: UserCompanies;
  laboratoryAnalyticalCompetences: LaboratoryAnalyticalCompetences;
}
export type KyselyMaestro = Kysely<DB>;

export const toSqlArray = <T extends string>(args: T[]) => {
  return sql<string[]>`ARRAY[${sql.join(args)}]` as Expression<T[]>;
};
