import { z } from 'zod';

export const Stage = z.enum(
  [
    'STADE1',
    'STADE2',
    'STADE3',
    'STADE4',
    'STADE5',
    'STADE6',
    'STADE7',
    'STADE8',
    'STADE9',
    'STADE10',
    'STADE11',
    'STADE12',
    'STADE13',
    'STADE14',
    'STADE15',
    'STADE16',
    'STADE17',
    'STADE18',
    'STADE19',
    'STADE20',
    'STADE21',
    'STADE22',
    'STADE23',
    'STADE24',
    'STADE25',
    'STADE26',
    'STADE27',
    'STADE28',
    'STADE29',
    'STADE30',
    'STADE31',
    'STADE32',
    'STADE33',
    'STADE34',
    'STADE35',
    'STADE36',
    'STADE37',
    'STADE38',
    'STADE39',
    'STADE40',
    'STADE41',
    'STADE42',
    'STADE43',
    'STADE44',
    'STADE45',
    'STADE46',
    'STADE47',
    'STADE48'
  ],
  {
    error: () => 'Veuillez renseigner le stade de prélèvement.'
  }
);

export type Stage = z.infer<typeof Stage>;

export const StageList = Stage.options;

export const StageLabels: Record<Stage, string> = {
  STADE1: 'Végétal au stade récolte',
  STADE2: 'Végétal en cours de culture (avant récolte)',
  STADE3: 'Végétal au stockage',
  STADE4: 'Aliment pour animaux',
  STADE5: 'Eau',
  STADE6: 'Intrant (spécialité commerciale ou bouillie)',
  STADE7: 'Produit végétal transformé',
  STADE8: 'Substrat',
  STADE9: 'Autre',
  STADE10: 'Abattoir',
  STADE11: 'Elevage pondeuse',
  STADE12: "Centre d'emballage",
  STADE13: 'Amont (fournisseur)',
  STADE14: 'Amont (usine)',
  STADE15: 'Commerce de détail',
  STADE16: 'Commerce de gros',
  STADE17: 'Conditionnement',
  STADE18: 'Distribution',
  STADE19: 'Distribution (détail)',
  STADE20: 'Distribution (détail, gros)',
  STADE21: 'Distribution (étal marché, etc.)',
  STADE22: 'Distribution (gros)',
  STADE23: 'Distribution (gros ou détail)',
  STADE24: 'Entrepôt',
  STADE25: 'Élevage',
  STADE26: 'Établissement de collecte',
  STADE27: 'Exploitation agricole (circuits formels et informels)',
  STADE28: 'Fabrication',
  STADE29: 'Fabrication (restauration)',
  STADE30: 'Ferme',
  STADE31: 'Gros',
  STADE32: 'Grossistes',
  STADE33: 'Import',
  STADE34: 'Importateur',
  STADE35: 'Importation',
  STADE36: 'Maraîcher',
  STADE37: 'Mise sur le marché',
  STADE38: 'Navires de pêche primaire, au débarquement',
  STADE39: 'Ns',
  STADE40: 'Prod. primaire',
  STADE41: 'Production',
  STADE42: 'Production primaire',
  STADE43: 'Torréfaction',
  STADE44: 'Transformation',
  STADE45: 'Tuerie',
  STADE46: 'Usine conserverie',
  STADE47: 'Usine de transformation',
  STADE48: 'Utilisation'
};
