export const MatrixList = [
  'Abricots',
  'Avocats',
  'Avoine',
  'Brèdes',
  'Carottes',
  'Céleris branches et raves',
  'Cerises',
  'Choux feuillus',
  'Choux-fleurs',
  'Endives chicons',
  'Fenouil',
  'Fèves et fèveroles',
  'Figues',
  'Fines herbes',
  'Laitues',
  'Légumineuses potagères sèches',
  'Lentilles sèches',
  'Litchis / ramboutans',
  'Mâche',
  'Mangues',
  'Navets',
  'Oignons bulbes',
  'Orge',
  'Patates douces',
  'Pavies, pêches, nectarines et brugnons',
  'Poireaux et oignons de printemps',
  'Poires',
  'Riz',
  'Soja (fèves)',
  'Tournesol',
];

export const MatrixPartList = ['Feuille', 'Fruit', 'Tige'];

export const MatrixKindList = [
  'A la récolte',
  'Au 1er stockage',
  'En cours de culture',
  'A partir de 2 mois après semis',
];
