import { Matrix } from './Matrix';

export const MatrixLabels: Record<Matrix, string> = {
  A00YZ: 'Houblon',
  A014C: 'Fruits à coque',
  A00PH: 'Fèves (non écossées)',
  A015L: 'Graines de tournesol',
  A00KR: 'Légumes-feuilles',
  A01LB: 'Avocats',
  A00FR: 'Choux-fleurs',
  A0DEH: 'Poireaux et similaires',
  A00GL: 'Choux verts et similaires',
  A00NE: 'Endives',
  A0DBP: 'Graines de tournesol et similaires',
  A0DVX: 'Abricots et similaires',
  A01GL: 'Pêches et similaires',
  A01JV: 'Litchis',
  A0DLB: 'Laitues et similaires',
  A0DFR: 'Fèves de soja (non écossées)',
  A01GG: 'Cerises et similaires',
  A00HC: 'Oignons',
  A00QH: 'Carottes',
  A001C: 'Riz et similaires',
  A00RE: 'Navets',
  A012R: 'Légumes secs (graines séchées de légumineuse)',
  A00SA: 'Fenouils',
  A01DP: 'Poires',
  A0D9Y: 'Orge et similaires',
  A01HG: 'Figues',
  A013Q: 'Lentilles (sèches)',
  A00RY: 'Céleris',
  A010C: 'Patates douces',
  A00MA:
    'Jeunes pousses (y compris les espèces du genre Brassica) et similaires',
  A00KT: 'Mâche',
  A000F: 'Avoine et similaires',
  A01LF: 'Mangues',
  A00GZ: 'Aulx',
  A00HF: 'Échalotes',
  A00RT: 'Asperges',
  A00JD: 'Aubergines',
  A01LC: 'Bananes communes',
  A001P: 'Grain de blé dur',
  A001R: "Grain d'épeautre",
  A00DL: "Grains d'avoine aplatis, complets",
  A001N: 'Grain de blé commun',
  A001M: 'Blé (froment)',
  A00FN: 'Brocolis',
  A010V: 'Canne à sucre',
  A03NJ: 'Cerises',
  A00TQ: 'Champignons de couche',
  A00FV: 'Choux de Bruxelles',
  A00FY: 'Choux pommés',
  A00FX: 'Choux pommés',
  A015M: 'Colza',
  A00JM: 'Concombres',
  A00JP: 'Cornichons',
  A00JR: 'Courgettes',
  A00JZ: 'Chayottes',
  A00JN: 'Cucurbitacés à peau comestible',
  A00LD: 'Endives',
  A00XB: 'Cerfeuils',
  A00XD: 'Ciboulettes',
  A00XA: 'Feuilles de céleri',
  A00YE: 'Persils',
  A017L: 'Sauge séchée',
  A00YF: 'Romarin',
  A00YQ: 'Thym',
  A00VV: 'Basilic',
  A00VX: 'Laurier',
  A00YP: 'Estragon',
  A00VT: 'Mélisse',
  A00XZ: 'Menthes',
  A00XV: 'Origan',
  A04MA: 'Fines herbes',
  A01EA: 'Fraises',
  A00PG: 'Haricots verts (non écossés)',
  A012A: 'Fèves (écossées)',
  A012G: 'Pois (écossés) et similaires',
  A0BAV: 'Pois chiches (écossés)',
  A012J: 'Petits pois (écossés)',
  A012B: 'Haricots et pois écossés frais',
  A00PX: 'Haricots et pois non écossés frais',
  A00PY: 'Petits pois (non écossés)',
  A00PZ: 'Pois chiches (non écossés)',
  A01JT: 'Kiwis',
  A00KX: 'Laitues (générique)',
  A00LE: 'Scaroles',
  A00KE: 'Melons',
  A01BQ: 'Olives',
  A01BR: 'Olives transformées',
  A01EE: 'Mûres de ronces',
  A01EP: 'Framboises (rouges ou jaunes)',
  A01EY: 'Myrtilles',
  A01FH: 'Airelles canneberges',
  A01FM: 'Groseilles à grappes (blanches, noires ou rouges)',
  A01DT: 'Petits fruits',
  A01FN: 'Groseilles noires',
  A0DQS: 'Pitaya / fruits du Dragon',
  A00JA: 'Poivrons doux',
  A00JB: 'Piments forts',
  A0DMM: 'Espèces cultivées de piment fort Capsicum annuum',
  A01DX: 'Raisins de table',
  A01DY: 'Raisins de cuve',
  A001D: 'Riz',
  A000N: 'Sarrasin',
  A000R: 'Grain de quinoa',
  A000L: 'Sarrasin/Quinoa',
  A00HQ: 'Tomates',
  A00HY: 'Tomates cerises',
  'A01QV#F28.A0C0S': 'Viande de bovin  non transformée',
  'A01RJ#F28.A0C0S': "Viande d'ovin non transformée",
  'A01RL#F28.A0C0S': 'Viande de caprin non transformée',
  'A01RG#F28.A0C0S': 'Viande de porcin non transformée',
  'A01SP#F28.A0C0S': 'Viande de poulets de chair non transformée',
  'A01SP#F31.A0CSD': 'Viande de poule de réforme non transformée',
  'A01SQ#F28.A0C0S': 'Viande de dinde non transformée',
  'A01SN#F26.A07XE': "Viande d'autres volailles non transformée",
  A031G: 'Oeuf de poule',
  A031K: 'Oeuf de caille',
  TODO1: 'Foie de bovin',
  TODO2: 'Chair de volaille'
};
