import type { Matrix } from './Matrix';

export const MatrixLabels = {
  A00YZ: 'Houblon',
  A014C: 'Fruits à coque',
  A00PH: 'Fèves (non écossées)',
  A015L: 'Graines de tournesol',
  A00KR: 'Légumes-feuilles',
  A00FR: 'Choux-fleurs',
  A0DEH: 'Poireaux et similaires',
  A00GL: 'Choux verts et similaires',
  A00NE: 'Endives',
  A0DBP: 'Graines de tournesol et similaires',
  A0DVX: 'Abricots et similaires',
  A01GL: 'Pêches et similaires',
  A01JV: 'Litchis',
  A0DLB: 'Laitues et similaires',
  A0DFR: 'Fèves de soja (non écossées)',
  A01GG: 'Cerises et similaires',
  A00HC: 'Oignons',
  A001C: 'Riz et similaires',
  A00RE: 'Navets',
  A012R: 'Légumes secs (graines séchées de légumineuse)',
  A00SA: 'Fenouils',
  A01DP: 'Poires',
  A0D9Y: 'Orge et similaires',
  A01HG: 'Figues',
  A013Q: 'Lentilles (sèches)',
  A00RY: 'Céleris branches',
  A010C: 'Patates douces',
  A000F: 'Avoine et similaires',
  A00GZ: 'Aulx',
  A00HF: 'Échalotes',
  A00RT: 'Asperges',
  A00JD: 'Aubergines',
  A01LC: 'Bananes communes',
  A001M: 'Blé (froment)',
  A00FN: 'Brocolis',
  A010V: 'Canne à sucre',
  A03NJ: 'Cerises',
  A00TQ: 'Champignons de couche',
  A00FV: 'Choux de Bruxelles',
  A00FY: 'Choux pommés',
  A00FX: 'Choux pommés',
  A015M: 'Colza',
  A00JM: 'Concombres',
  A00JP: 'Cornichons',
  A00JR: 'Courgettes',
  A00JZ: 'Chayottes',
  A00JN: 'Cucurbitacés à peau comestible',
  A00LD: 'Endives',
  A00XB: 'Cerfeuils',
  A00XD: 'Ciboulettes',
  A00XA: 'Feuilles de céleri',
  A00YE: 'Persils',
  A017L: 'Sauge séchée',
  A00YF: 'Romarin',
  A00YQ: 'Thym',
  A00VV: 'Basilic',
  A00VX: 'Laurier',
  A00YP: 'Estragon',
  A00VT: 'Mélisse',
  A00XZ: 'Menthes',
  A00XV: 'Origan',
  A04MA: 'Fines herbes',
  A01EA: 'Fraises',
  A00PG: 'Haricots verts (non écossés)',
  A012A: 'Fèves (écossées)',
  A012G: 'Pois (écossés) et similaires',
  A0BAV: 'Pois chiches (écossés)',
  A012J: 'Petits pois (écossés)',
  A012B: 'Haricots et pois écossés frais',
  A00PX: 'Haricots et pois non écossés frais',
  A00PY: 'Petits pois (non écossés)',
  A00PZ: 'Pois chiches (non écossés)',
  A01JT: 'Kiwis',
  A00KX: 'Laitues (générique)',
  A00LE: 'Scaroles',
  A00KE: 'Melons',
  A01BQ: 'Olives',
  A01BR: 'Olives transformées',
  A01EE: 'Mûres de ronces',
  A01EP: 'Framboises (rouges ou jaunes)',
  A01EY: 'Myrtilles',
  A01FH: 'Airelles canneberges',
  A01FM: 'Groseilles à grappes (blanches, noires ou rouges)',
  A01DT: 'Petits fruits',
  A01FN: 'Groseilles noires',
  A0DQS: 'Pitaya / fruits du Dragon',
  A00JA: 'Poivrons doux',
  A00JB: 'Piments forts',
  A0DMM: 'Espèces cultivées de piment fort Capsicum annuum',
  A01DX: 'Raisins de table',
  A01DY: 'Raisins de cuve',
  A001D: 'Riz',
  A000N: 'Sarrasin',
  A000R: 'Grain de quinoa',
  A000L: 'Sarrasin/Quinoa',
  A00HQ: 'Tomates',
  A00HY: 'Tomates cerises',
  'A01QV#F28.A0C0S': 'Viande de bovin non transformée',
  'A01RJ#F28.A0C0S': "Viande d'ovin non transformée",
  'A01RL#F28.A0C0S': 'Viande de caprin non transformée',
  'A01RG#F28.A0C0S': 'Viande de porcin non transformée',
  'A01SP#F28.A0C0S': 'Viande de poulets de chair non transformée',
  'A01SP#F31.A0CSD': 'Viande de poule de réforme non transformée',
  'A01SQ#F28.A0C0S': 'Viande de dinde non transformée',
  'A01SN#F26.A07XE': "Viande d'autres volailles non transformée",
  A031G: 'Oeuf de poule',
  A031K: 'Oeuf de caille',
  'A01XF#F28.A0C0S': 'Foie de bovin non transformé',
  A01HQ: 'Kakis',
  A01CX: 'Pamplemousses et similaires',
  A0DQN: 'Avocats à huile',
  A0DPL: 'Taros bleus',
  A01LQ: "Fruits de l'arbre à pain",
  A01HR: 'Plaquemines de Chine',
  A0DDD: 'Truffes noires/Truffes du Périgord',
  A003Z: 'Farine Graham',
  A01LS: 'Durions',
  A0BB0: 'Grain de cheval (graines fraîches)',
  A004D: 'Farine à chapati',
  A0BB1: 'Lentille de terre (graines fraîches)',
  A00LQ: 'Feuilles de moutarde brune',
  A0CHE: 'Vanille de Tahiti',
  A003Q: 'Son de seigle',
  A00LP: 'Roquette sauvage/Roquette jaune',
  A00VD: 'Laitue de mer',
  A015K: 'Graines de sésame',
  A0DCP: 'Autres algues',
  A01LR: 'Pomme de jacque',
  A00ZY: 'Légumes-racines et tubercules tropicaux',
  A00GN: 'Choux fourragers',
  A019J: 'Tamarin',
  A00DS: 'Flocons transformés à base de riz',
  A000E: 'Grain de petit millet',
  A01LH: 'Grenades',
  A00QK: 'Racines de raifort',
  A00DA: "Flocons transformés à base d'orge",
  A003T: 'Farine de sorgho',
  A004B: 'Farine de blé, complète',
  A0CYB: 'Racines de temoe-lawacq',
  A0DKS: 'Graines germées de gingembre',
  A00QL: 'Racines de raifort',
  A0DCX: 'Autres espèces du genre Tuber, non désignées par ailleurs ',
  A01LG: 'Papayes',
  A00ZV: 'Pommes de terre hâtives',
  A0DRA: 'Curubas',
  A0DQJ: 'Bananes plantains - acuminata (espèce cultivée)',
  A00QV: 'Radis',
  A01AF: "Racines de l'ase fétide",
  A010N: 'Racines de chayotte',
  A0DPY: 'Goyaves de Sartori',
  A170N: 'Yellow pitayas',
  A0DFA: 'Lupin blanc (écossé)',
  A00RC: 'Scorsonères',
  A0DMR: 'Baies de lyciet commun',
  A003M: 'Farine de seigle, complète',
  A0DZB: 'Oranges',
  A01GY: 'Prunes du Japon',
  A00ZZ: 'Racines de manioc',
  A001K: 'Seigle',
  A01JX: 'Mangoustans',
  A00LN: 'Roquette',
  A012Q: 'Pois bambara (graines fraîches)',
  A00VC: 'Wakamé',
  A00VL: 'Hijiki',
  A01KC: 'Fruits de la passion',
  A00RQ: 'Chervis/Chirous',
  A015T: 'Graines de moutarde fourragère',
  A00ST: 'Graines germées et pousses de pois',
  A0F6P: 'Son de riz',
  A010A: 'Tannies',
  A0DCZ: "Truffes d'été",
  A00KH: 'Potirons',
  A00DK: "Flocons d'avoine à forte teneur en son",
  A0DPS: 'Autres espèces du genre Artocarpus, non désignées par ailleurs',
  A004L: "Farine d'épeautre, complète",
  A0DQV: 'Grenadilles sauvages',
  A0DLR: 'Courges-potirons',
  A0DQG: 'Bananes - paradisiaca (espèce cultivée)',
  A00QY: 'Daïkon',
  A01DJC: 'Pommes à cidre',
  A01GV: 'Prunes Chickasaw ',
  A01GX: 'Reines-claudes',
  A0DQX: 'Fruits du faux philodendron/Cérimans',
  A00HM: 'Kurrat',
  A00SH: 'Graines germées de luzerne cultivée',
  A015R: 'Graines de Canola',
  A010M: 'Rhizomes de petit galanga',
  A0DKT: 'Graines germées de daïkon',
  A01DJ: 'Pommes de table',
  A015J: 'Graines de pavot',
  A01LP: 'Ananas',
  A0DBK: 'Graines de moutarde blanche',
  A0CHF: 'Vanillon',
  A0DQR: 'Fruits du cactus saguaro',
  A01LT: 'Corossols',
  A000A: 'Grain de teff',
  A002K: 'Orge perlé',
  A000B: "Grain d'éleusine",
  A010L: 'Rhizomes de grand galanga',
  A00RH: 'Oxalide crénelée',
  A00DL: 'Triticale',
  A0DPX: 'Goyaves de para',
  A01GT: 'Prunes-cerises ',
  A00VG: 'Goémons blancs',
  A01GQ: 'Prunes',
  A003B: "Son d'avoine",
  A0DKV: 'Graines germées de brocolis',
  A00QZ: 'Souchets comestibles/Amandes de terre',
  A012P: 'Arachides (graines fraîches)',
  A0DRC: 'Fruits du marula',
  A0DVJ: 'Prunes maritimes',
  A0CYD: 'Racines de curcuma rond',
  A00KN: 'Courges à la cire',
  A00VF: 'Eucheuma',
  A002G: 'Farine de sarrasin',
  A00GP: 'Feuilles de chou-rave',
  A0DPJ: 'Eddoes/Taros chinois',
  A00SR: 'Graines germées de haricot mungo',
  A01GZ: 'Prunelles',
  A0DCT: "Mousses d'Islande/Cétraires d'Islande/Lichens d'Islande",
  A004A: 'Farine de blé, brune',
  A01KY: 'Fève Tonka',
  A01JM: 'Jujubes communs',
  A01GM: 'Pêches communes',
  A010K: 'Fruits du canna (balisier rouge)',
  A0DCN: 'Autres organismes procaryotes',
  A0DEY: 'Lupin jaune (écossé)',
  A01DF: 'Autres agrumes',
  A0DQB: 'Goyaves du Brésil',
  A00ED: 'Son de blé aplati en flocons',
  A0CHH: 'Racines de raifort du Japon (wasabi)',
  A01LF: 'Mangues',
  A00QQ: 'Topinambours',
  A004Q: 'Germe de blé',
  A0DQY: 'Grenadelles/Grenadilles sucrées/Grenadilles douces',
  A0DNZ: 'Mini-carottes',
  A0DLD: 'Choux à faucher',
  A00RB: "Salsifis espagnols (chardons d'Espagne)",
  A00KT: 'Mâche',
  A012L: 'Lentilles (écossées)',
  A042B: 'Salades',
  A004J: "Farine d'épeautre, raffinée",
  A0DVG: 'Plumcots',
  A00MA:
    'Jeunes pousses (y compris les espèces du genre Brassica) et similaires',
  A0DPK: 'Dachines',
  A170R: 'Pale-leaf sunflower',
  A00DY: 'Flocons transformés à base de seigle',
  A00QE: 'Lentilles (jeunes gousses)',
  A0DMQ: 'Baies de lyciet de Chine',
  A016K: 'Germes de maïs',
  A00SY: 'Graines germées de soja',
  A0DEX: 'Lupin des Andes (écossé)',
  A0DCQ: 'Spirulina platensis',
  A01AB: 'Racines de gingembre',
  A00VN: 'Spaghetti de mer',
  A00QJ: 'Céleris-raves',
  A01GF: 'Abricots',
  A001P: 'Blé dur',
  A01LY: 'Feijoas',
  A00QP: 'Racines de gentiane',
  A0DCR: 'Spirulina maxima',
  A0DQH: 'Bananes plantains - balbisiana (espèce cultivée)',
  A001R: 'Epeautre',
  A00RL: 'Grande bardane ou bardane comestible',
  A001L: 'Sorgho',
  A002P: 'Semoule de maïs',
  A01HA: "Prunes d'Amérique",
  A0DKX: 'Graines germées de ciboulette chinoise',
  A001B: 'Grain de millet commun',
  A004C: 'Farine de blé dur',
  A0CHG: 'Racines de zédoaire',
  A0CGB: 'Langsats',
  A01BX: 'Citrons et similaires',
  A0DQD: 'Asimines',
  A0DCS: 'Autres mousses et lichens',
  A01AC: 'Racines de curcuma',
  A000G: 'Avoine',
  A00SB: 'Poireaux',
  A004S: 'Mélange de farine (blé/seigle/orge/avoine et autre)',
  A00GQ: 'Choux à grosses côtes',
  A00VM: 'Kombu',
  A0DNJ: 'Petits radis ',
  A0DLE: 'Choux (géants) de Jersey',
  A00SZ: 'Graines germées et pousses de tournesol',
  A001N: 'Froment',
  A0DKR: 'Graines germées de roquette',
  A01KQ: 'Longanes',
  A170S: 'Tuberous peas',
  A0DVH: 'Prunes Klamath',
  A0CXQ: 'Betteraves sucrières et similaires',
  A00VH: 'Laitue rouge',
  A002Q: 'Farine de maïs',
  A01AA: 'Racines de réglisse',
  A003N: 'Farine de seigle, sans gluten',
  A170Z: 'Rockweed',
  A176G: 'Baels',
  A00QH: 'Carottes',
  A004K: "Farine d'épeautre, semi-complète",
  A01AJ: 'Rhizomes de galingale',
  A00EM: 'Flocons transformés à base de céréales mélangées',
  A0F4Q: 'Céréales pour petit-déjeuner extrudées',
  A0DPZ: 'Goyaves du Costa Rica',
  A01KX: 'Quenettes',
  A000T: 'Maïs (grain et semence)',
  A00KP: 'Maïs doux',
  A00ZX: 'Pommes de terre non hâtives',
  A000D: 'Grain de millet des oiseaux',
  A002E: "Farine d'amarante",
  A00YT: "Cresson d'hiver",
  A0DPA: 'Variétés de carottes de couleur',
  A00QX: 'Radis noir',
  A0DVL: 'Pêches plates',
  A0DPN: 'Racines de konjac',
  A0DQA: 'Goyaves de Chine/Goyages-fraises',
  A0CGK: 'Grain de fonio noir',
  A00MJ: 'Épinards',
  A00RP: 'Racines de raiponce cultivée',
  A04KT:
    'Farines de céréales et de grains de type céréale non mentionnées séparément.',
  A000Z: 'Millet pied-de-coq',
  A01GR: 'Prunes de Damas/Quetsches',
  A003K: 'Farine de seigle, raffinée',
  A0DNK: 'Racines de maca',
  A01GS: 'Mirabelles',
  A0BJZ: "Grain d'alpiste",
  A00EC: 'Germes de blé aplatis en flocons',
  A00LL: 'Cressons de terre',
  A003F: 'Farine de riz',
  A01HZ: 'Tamarillos/Tomates arbustives',
  A00TA: 'Graines germées de blé',
  A0DBL: 'Graines de moutarde noire',
  A0CGC: 'Salaks/fruits-serpents',
  A01KN: 'Akées/Akis',
  A0DLT: 'Doubeurres/Courges musquées/Courges butternut ',
  A170V: 'Choux kale',
  A170P: 'Orris root',
  A002A: 'Grain de Larme-de-Job',
  A00RS: 'Artichauts',
  A003Y: 'Farine de blé, blanche',
  A01GN: 'Brugnons et nectarines',
  A001A: 'Grain de millet perlé',
  A01KS: 'Naranjillas/Narangilles',
  A01KD: 'Figues de Barbarie',
  A002Y: "Farine d'avoine",
  A0DQZ: 'Barbadines',
  A00VJ: 'Dulse',
  A001Y: 'Autres céréales',
  A01CB: 'Mandarines et similaires',
  A002T: 'Farine de millet',
  A00DD: 'Flocons transformés à base de maïs',
  A0DEZ: 'Lupin bleu (écossé)',
  A004P: 'Son de blé',
  A003L: 'Farine de seigle, semi-complète',
  A0DDC: 'Truffes blanches/Truffes grises/Truffes des Provenà§aux',
  A00GM: 'Choux verts frisés',
  A019H: 'Vanille',
  A0DNX: 'Racines de pissenlit',
  A002L: "Farine d'orge",
  A170Q: 'Mashua',
  A001Z: 'Grain de fonio blanc',
  A00KJ: 'Pastèques',
  A0CYC: 'Rhizomes de galanga',
  A0CGD: 'Goyaves',
  A00RA: 'Salsifis',
  A01LB: 'Avocats',
  A00RN: 'Crosnes du Japon',
  TODO_1: 'Additif, prémélange',
  TODO_2: 'Algues',
  TODO_3: 'Algues, halophytes, aliments en contenant',
  TODO_4: 'Algues, halophytes, aliments en contenant - uniquement mp algues',
  TODO_5: 'Aliment',
  TODO_6: "Aliment (y compris aliment d'allaitement)",
  TODO_7: 'Aliment composé autre (lapin ou cheval)',
  TODO_8: 'Aliment composé autre (lapin)',
  TODO_9: 'Aliment composé petfood',
  TODO_10: 'Aliment composé petfood autre',
  TODO_11:
    'Aliment composé petfood autre - uniquement mélanges de graines pour oiseaux (graines entières)',
  TODO_12: 'Aliment composé petfood carnivore domestique',
  TODO_13:
    'Aliment composé petfood carnivores domestiques - aliments secs (croquettes) uniquement',
  TODO_14: 'Aliment composé poisson (aquaculture)',
  TODO_15: 'Aliment composé porcins',
  TODO_16: 'Aliment composé ruminants',
  TODO_17: 'Aliment composé veau, agneau, chevreau',
  TODO_18: 'Aliment composé volailles',
  TODO_19:
    "Aliment liquide (notamment d'allaitement) ou à défaut eau de boisson",
  TODO_20: 'Aliment liquide (ou à défaut eau de boisson)',
  TODO_21: 'Aliment médicamenteux',
  TODO_22: 'Aliments minéraux',
  TODO_23: 'Aliments pour bébés',
  TODO_24: 'Aliments pour bébés : compotes de pomme',
  TODO_25: 'Aliments pour bébés contenant de la pomme de terre',
  TODO_26:
    'Aliments pour bébés contenant des légumes-feuilles (cresson, endive, salades, blette, choux, épinard)',
  TODO_27:
    "Amandes d'abricots et les amandes non transformées entières, broyées, moulues ou concassées (mises sur le marché pour le consommateur final)",
  TODO_28: 'Amandes d’abricots, amandes, produits transformées à base d’amande',
  TODO_29: 'Ananas',
  TODO_30: 'Aubergines',
  TODO_31: 'Autres aliments composés (lapin, cheval, etc.)',
  TODO_32: 'Autres pièces cuites',
  TODO_33: 'Autres poissons fumés',
  TODO_34:
    'Autres produits et sous-produits végétaux ; produits de fermentation',
  TODO_35:
    'Autres produits et sous-produits végétaux ; produits de fermentation - herbes et plantes aromatiques uniquement',
  TODO_36: 'Avoine non cuit',
  TODO_37: 'Avoine non cuit (en grains)',
  TODO_38: 'Baies rouges fraîches',
  TODO_39: 'Baies rouges surgelées',
  TODO_40: 'Bananes',
  TODO_41: 'Blé (en grains, non transformé, non étuvé)',
  TODO_42: 'Blé dur non cuit',
  TODO_43: 'Blé dur non cuit (en grains)',
  TODO_44: 'Blé tendre non cuit',
  TODO_45: 'Blé tendre non cuit (en grains)',
  TODO_46: 'Boissons alcoolisées : bières',
  TODO_47: 'Boissons alcoolisées : cidres',
  TODO_48: 'Boissons alcoolisées : spiritueux',
  TODO_49: 'Boissons alcoolisées : spiritueux à base de pomme',
  TODO_50: 'Boissons alcoolisées : vins et produits similaires',
  TODO_51: 'Boissons conditionnées en pet recyclé',
  TODO_52: 'Bovin : graisse périrénale',
  TODO_53: 'Bovin : muscle+foie',
  TODO_54: 'Boyaux',
  TODO_55:
    'Brassicacées (ex : chou, chou chinois, chou-fleur, chou-kale, brocoli)',
  TODO_56: 'Brocolis',
  TODO_57: 'Cacao',
  TODO_58: 'Caecum',
  TODO_59: 'Cafés torréfiés (en grains, moulus, instantanés)',
  TODO_60: 'Caprin : graisse périrénale',
  TODO_61: 'Caprin : muscle+foie',
  TODO_62: 'Carottes',
  TODO_63: 'Chair',
  TODO_64: 'Chair + peau',
  TODO_65: 'Chair blanche',
  TODO_66: 'Champignons',
  TODO_67: 'Chicorée',
  TODO_68: 'Chips de banane',
  TODO_69: 'Chips de légumes (sauf pomme de terre)',
  TODO_70: 'Chips de pomme de terre',
  TODO_71: 'Chocolats au lait',
  TODO_72: 'Chocolats noirs',
  TODO_73: 'Choux fleurs',
  TODO_74: 'Clémentines/mandarines',
  TODO_75: 'Complément alimentaire',
  TODO_76: "Complément alimentaire à base d'huile de poisson",
  TODO_77: "Complément alimentaire à base d'huile poisson",
  TODO_78: 'Complément alimentaire à base de levure de riz rouge',
  TODO_79: 'Complément alimentaire à base de macro-algues séchées',
  TODO_80: 'Complément alimentaire à base de plantes séchées',
  TODO_81: 'Complément alimentaire à base de pollen',
  TODO_82:
    'Compléments alimentaires contenant de la propolis, de la gelée royale ou de la spiruline',
  TODO_83:
    'Compléments alimentaires ou denrées susceptible de contenir des had',
  TODO_84: "Compléments alimentaires à base d'argile",
  TODO_85: 'Compléments alimentaires à base de levure de riz rouge',
  TODO_86: 'Compléments alimentaires à base de plantes séchées',
  TODO_87: 'Compléments alimentaires à base de pollen',
  TODO_88: 'Compotes',
  TODO_89: 'Compotes de pomme',
  TODO_90: 'Concombres',
  TODO_91:
    'Confiserie, dragées, pâtisseries avec glaçage,- boissons en poudre, sirop de noix de coco...- sauce blanche de type « fast food », - produits alimentaires avec un colorant blanc/couleur pale importés des pays tiers',
  TODO_92: 'Confiseries',
  TODO_93: 'Confiseries à base de réglisse',
  TODO_94:
    'Confiseries,micro-confiseriesdestinées àrafraîchirl’haleine,gommes àmâcher, boissonscontenant de lamenthe ou de lamenthe poivrée',
  TODO_95: 'Courgettes',
  TODO_96: 'Crackers de riz',
  TODO_97: 'Crevettes',
  TODO_98: 'Crevettes cuites',
  TODO_99: 'Cumin et herbes séchées',
  TODO_100: 'Céréales brutes',
  TODO_101: 'Céréales et produits dérivés, hors maïs',
  TODO_102:
    'Céréales et produits dérivés, hors maïs - graines entières (cibler sorgho, millet)',
  TODO_103:
    'Céréales et produits dérivés, hors maïs - graines entières céréales et dérivés',
  TODO_104:
    'Céréales pour petit-déjeuner et collations à base de céréales collation céréale',
  TODO_105:
    'Céréales pour petit-déjeuner et collations à base de céréales collations base',
  TODO_106:
    'Céréales pour petit-déjeuner et collations à base de céréales collations céréales',
  TODO_107: 'Céréales produites sur l’exploitation',
  TODO_108:
    "Céréales produites sur l’exploitation (céréales non broyées/non moulues pour l'ergot de seigle)",
  TODO_109: 'Daoa / daov',
  TODO_110: "Daov d'origine hors fr",
  TODO_111: 'Denrées alimentaires déshydratées déclassées',
  TODO_112: 'Denrées susceptibles de contenir des substances médicamenteuses',
  TODO_113: 'Denrées transformés boissons',
  TODO_114: "Drêches directement livrées à l'élevage",
  TODO_115: 'Eau boisson',
  TODO_116: 'Eau de mer',
  TODO_117: 'Ensilage',
  TODO_118: 'Epinards',
  TODO_119: 'Farine de poisson',
  TODO_120: 'Farine de sang ou produits sanguins',
  TODO_121: 'Farines blanches autres que de blé et farines complètes',
  TODO_122: 'Farines de blé blanches',
  TODO_123:
    'Fines herbes (ex : basilic, sauge, thym, menthe, laurier, origan, estragon, aneth)',
  TODO_124:
    'Fines herbes fraiches, non déshydratées (ex : basilic, ciboulette, sauge, thym, menthe, laurier, origan, estragon, aneth)',
  TODO_125: 'Foie',
  TODO_126: 'Foie (ou à défaut muscle)',
  TODO_127: 'Foie ou muscle',
  TODO_128: 'Fourrages',
  TODO_129: 'Fourrages déshydratés ( betterave,…)',
  TODO_130: 'Fourrages déshydratés (luzerne, betterave,...)',
  TODO_131: 'Fourrages ou ensilages',
  TODO_132: 'Fraises',
  TODO_133: 'Frites prêtes à consommer',
  TODO_134: 'Fromages fumés',
  TODO_135: 'Fromages à pâte dure',
  TODO_136: 'Fruit',
  TODO_137: 'Fruits découpés',
  TODO_138: 'Fruits et leurs dérivés en conserve',
  TODO_139: 'Fruits et légumes',
  TODO_140: 'Fruits frais',
  TODO_141: 'Fruits frais ou congelés',
  TODO_142: 'Fruits rouges(hors fraises et cerises)',
  TODO_143: 'Fruits séchés',
  TODO_144: 'Fruits à coque et dérivés (hors pistaches et amandes)',
  TODO_145: 'Fruits à coque et leurs dérivés',
  TODO_146: 'Fruits à coque et leurs dérivés primaires',
  TODO_147: 'Fruits à coque torréfiés',
  TODO_148: 'Fèces',
  TODO_149: 'Gibier',
  TODO_150: 'Gibier d’élevage : muscle',
  TODO_151: 'Gibier d’élevage : muscle + foie',
  TODO_152: 'Gonades',
  TODO_153: 'Graines de chanvre',
  TODO_154: 'Graines de chanvre ou de tournesol',
  TODO_155: 'Graines de lin',
  TODO_156: 'Graines de lin, tourteaux de lin & aliments en contenant',
  TODO_157: 'Graines de pavot',
  TODO_158: 'Graines de tournesol',
  TODO_159: 'Graines et fruits oléagineux',
  TODO_160: 'Graines oléagineuses',
  TODO_161: 'Graines torréfiées',
  TODO_162: 'Graisse (+/- peau)',
  TODO_163: 'Graisse fondue',
  TODO_164: 'Graisse péri-rénale',
  TODO_165: 'Graisse périrénale',
  TODO_166: 'Graisse périrénale (à défaut rein+graisse périrénale)',
  TODO_167: 'Graisse périrénale ou muscle',
  TODO_168: 'Graisses et huiles animales et marines',
  TODO_169: 'Gélatine',
  TODO_170: 'Gélule avec colorant blanc',
  TODO_171: 'Hareng',
  TODO_172: 'Haricots secs',
  TODO_173: 'Haricots verts',
  TODO_174: 'Huile de poisson',
  TODO_175: 'Huiles de poisson',
  TODO_176: 'Huiles et graisses végétales et leurs dérivés',
  TODO_177: 'Huiles issues de graines de chanvre',
  TODO_178: 'Huiles végétales (hors olives vierges)',
  TODO_179: 'Huiles végétales et dérivés (acides gras, etc.)',
  TODO_180: 'Huiles végétales non raffinées',
  TODO_181: 'Infusions et ingrédients pour infusions',
  TODO_182: 'Infusions à base de feuilles',
  TODO_183: 'Infusions à base de feuilles de chanvre',
  TODO_184: 'Jambons secs',
  TODO_185: "Jus d'orange (100% orange)",
  TODO_186: 'Jus de fruits, de légumes, nectars, boissons à base de plantes',
  TODO_187: 'Jus de pomme artisanal',
  TODO_188: 'Jus fruits/légumes',
  TODO_189: 'Jus à base de raisin',
  TODO_190: 'Kiwis',
  TODO_191: 'Lait cru de brebis',
  TODO_192: 'Lait cru de chèvre',
  TODO_193: 'Lait cru de vache',
  TODO_194: 'Lait cru entier',
  TODO_195: 'Lait de brebis cru',
  TODO_196: 'Lait de chèvre cru',
  TODO_197: 'Lait de vache cru',
  TODO_198: 'Laitues et autres salades',
  TODO_199: 'Langoustines',
  TODO_200: 'Lapin : muscle',
  TODO_201: 'Lapin : muscle + foie',
  TODO_202: 'Legume feuille',
  TODO_203: 'Lentilles (sèches)',
  TODO_204: 'Lupins (secs) et similaires',
  TODO_205: 'Légumes bulbes (ex : ail, oignon, ciboule, échalotte)',
  TODO_206: 'Légumes bulbes (ex : ciboulette, ail, oignon, ciboule, échalotte)',
  TODO_207: 'Légumes et leurs dérivés dans une conserve en métal',
  TODO_208:
    'Légumes feuilles (les endives ne peuvent être prélevées que si elles sont cultivées en pleine terre à l’extérieur et non sous abri)',
  TODO_209: 'Légumes feuilles frais',
  TODO_210: 'Légumes racinaires tubercule',
  TODO_211:
    'Légumes racines, tubercules tropicaux(ex: manioc, patate douce, christophine, taro, dachine)',
  TODO_212:
    'Légumes-feuilles (ex : artichaut, céleri, épinard, fenouil, endive, laitue, roquette, blette, choux)',
  TODO_213:
    'Légumes-feuilles (ex : épinard, endive, laitue, roquette, blette, choux)',
  TODO_214:
    'Légumes-fruits (ex : aubergine, avocat, citrouille, courge, piment,  poivron, potiron, tomate, concombre, olive)',
  TODO_215:
    'Légumes-fruits (ex : aubergine, citrouille, courge, piment doux,  poivron doux, potiron, tomate, concombre, melo, pastèque)',
  TODO_216:
    'Légumes-racines (ex : carotte, panais, betterave, navet, radis, céleri-rave, salsifis',
  TODO_217:
    'Légumes-tiges (ex : artichaut, céleris, asperge, cœur de palmier, fenouille, rhubarbe, poireau, pousses de bambou)',
  TODO_218:
    'Légumes-tiges (ex : cœur de palmier, fenouille, rhubarbe, poireau, pousses de bambou)',
  TODO_219: 'Légumineuses potagères',
  TODO_220: 'Légumineuses potagères fraiches (ex : haricots, pois, lentilles)',
  TODO_221: 'Légumineuses séchées et leurs dérivés primaires',
  TODO_222: 'Mangues',
  TODO_223: "Matière première d'origine minérale",
  TODO_224:
    "Matière première d'origine minérale directement livrées en élevage",
  TODO_225:
    'Matrices recommandées:avocatsbananes plantincéleriscerisescitrons vertscressonsfeuilles de vignefiguesfruits de la passion/maracujasgoyavesgrenadesherbes aromatiques fraichespimentspitaya (fruit du dragon)pois (non écossés)/ pois chiche',
  TODO_226: 'Maïs (grains) non cuit',
  TODO_227: 'Maïs (hors fourrage) et produits dérivés',
  TODO_228: 'Maïs et produits dérivés',
  TODO_229: 'Maïs et produits dérivés - graines entières',
  TODO_230: 'Maïs non cuit (en grains)',
  TODO_231: 'Maïs ou blé grains',
  TODO_232: 'Melons',
  TODO_233: 'Miel',
  TODO_234: "Miel (hors miel d'arbre)",
  TODO_235: 'Millet (grains) non cuit',
  TODO_236: 'Millet non cuit (en grains)',
  TODO_237: 'Mollusques bivalves',
  TODO_238: 'Moutardes',
  TODO_239: 'Mouture (farine) de blé dur',
  TODO_240: 'Mouture (farine) de blé tendre',
  TODO_241: 'Muscle',
  TODO_242: 'Muscle ou foie',
  TODO_243: 'Muscle+foie',
  TODO_244: 'Nougats, massepain',
  TODO_245: 'Oeil (rétine)+poumon',
  TODO_246: 'Oignons',
  TODO_247:
    'Oléagineux, protéagineux (tourteaux, etc.) - graines entières (cibler tournesol, soja)',
  TODO_248: 'Oléagineux, protéagineux et produits dérivés (tourteaux, etc.)',
  TODO_249:
    'Oléagineux, protéagineux et produits dérivés (tourteaux, etc.) - colza uniquement',
  TODO_250:
    'Oléagineux, protéagineux et produits dérivés (tourteaux, etc.) - hors soja',
  TODO_251: 'Oranges',
  TODO_252: 'Orge (grains) non cuit',
  TODO_253: 'Orge non cuit (en grains)',
  TODO_254: 'Ovin : graisse périrénale',
  TODO_255: 'Ovin : muscle+foie',
  TODO_256: 'Ovoproduits/produits laitiers',
  TODO_257: 'Pain',
  TODO_258: "Pat de porcs, volaille ou insectes destinées à l'aquaculture",
  TODO_259: 'Pat d’insectes',
  TODO_260: 'Pat porc, volailles, insecte',
  TODO_261: 'Pat porcs, volailles, insectes, ruminants',
  TODO_262: 'Pistaches',
  TODO_263: 'Plante aromatique',
  TODO_264: 'Plats pour personnes âgées',
  TODO_265: 'Poil',
  TODO_266: 'Poireaux',
  TODO_267: 'Poires',
  TODO_268: 'Pommes',
  TODO_269: 'Pommes de terre',
  TODO_270: 'Pommes de terre fraîches',
  TODO_271: 'Porcin : graisse périrénale',
  TODO_272: 'Porcin : muscle+foie',
  TODO_273: 'Poudre de cacao non sucrée',
  TODO_274: 'Poumon',
  TODO_275: 'Produit de la pêche - crustacé : chair',
  TODO_276: 'Produit de la pêche - céphalopode : chair',
  TODO_277: 'Produit de la pêche - mollusque : chair',
  TODO_278:
    "Produit de la pêche - poisson d'aquaculture eau douce ou eau de mer : chair",
  TODO_279:
    "Produit de la pêche - poisson d'eau douce sauvage ou élevage : chair",
  TODO_280: 'Produit de la pêche - poisson de mer sauvage ou élevage : chair',
  TODO_281: 'Produits contenant des graines de pavot',
  TODO_282: 'Produits de boulangerie : beignets, churros (minimum 5% mg)',
  TODO_283: 'Produits de boulangerie : beignets, crackers, biscottes',
  TODO_284: 'Produits de boulangerie : pains',
  TODO_285: 'Produits de boulangerie : pains, beignets, crackers, biscottes',
  TODO_286: 'Produits de boulangerie fine : biscuits, gâteaux, viennoiseries',
  TODO_287:
    'Produits de boulangerie fine : biscuits, gâteaux, viennoiseries, beignets, crackers, biscottes',
  TODO_288: 'Produits de boulangerie fine : viennoiseries',
  TODO_289: 'Produits de charcuterie',
  TODO_290:
    'Produits de céréales et de boulangerie (farine de céréales, pains)',
  TODO_291: 'Produits de la pêche fumés',
  TODO_292: "Produits de mouture d'avoine",
  TODO_293: "Produits de mouture d'orge",
  TODO_294: "Produits de mouture d'épeautre",
  TODO_295: 'Produits de mouture de blé dur',
  TODO_296: 'Produits de mouture de blé tendre',
  TODO_297: 'Produits de mouture de maïs',
  TODO_298: 'Produits de mouture de millet',
  TODO_299: 'Produits de mouture de sarrasin',
  TODO_300: 'Produits de mouture de seigle',
  TODO_301: 'Produits de mouture de sorgho',
  TODO_302: 'Produits dérivés de la tomate',
  TODO_303: 'Produits sucrés',
  TODO_304:
    'Produits suivants contenant de la réglisse :bonbons, boissons anisées, infusions, glaces',
  TODO_305:
    'Produits suivants présentant une coloration jaune-orangé : confiseries et produits sucrés,boissonsyaourts et glaces aromatisés, confitures,charcuteries (saucisses, chorizo), poissons fumés,glaçages, crèmes',
  TODO_306:
    'Produits suivants présentant une coloration rouge : confiseries et produits sucrés,boissonsyaourts et glaces aromatisés, confitures,charcuteries (saucisses, chorizo),glaçages, crèmes',
  TODO_307:
    'Produits suivants « sans sucre » ou « allégé » : confiseries, boissons, confitures, desserts, pâtes à tartiner',
  TODO_308: 'Produits à base de graines',
  TODO_309: 'Produits à base de sarrasin, millet ou maïs',
  TODO_310: 'Produits à cuire',
  TODO_311: 'Produits à poêler réfrigérés',
  TODO_312: 'Produits à poêler surgelés',
  TODO_313: "Prémélange d'additifs",
  TODO_314:
    'Préparation pour nourrisson et enfants en bas âge à base de céréales',
  TODO_315:
    'Préparations pour enfants en bas âge - aliments pour bébés (petits pots de fruits ou légumes sans viande ni poisson)',
  TODO_316:
    'Préparations pour enfants en bas âge - laits infantiles 1er et 2ème âge',
  TODO_317:
    'Préparations pour enfants en bas âge - préparations à base de céréales',
  TODO_318:
    'Préparations pour nourrissons, de suite ou pour enfants en bas âge',
  TODO_319:
    "Préparations pour nourrissons, de suite ou pour enfants en bas âge - laits infantiles - (liquide prêt à l'emploi)",
  TODO_320:
    'Préparations pour nourrissons, de suite ou pour enfants en bas âge - laits infantiles - (poudre / conserve en métal)',
  TODO_321: 'Préparations à base de céréales pour nourrissons',
  TODO_322:
    'Préparations à base de céréales pour nourrissons (conserve en métal)',
  TODO_323:
    'Préparations à base de céréales pour nourrissons à base de maïs, sorgho, millet ou sarrasin',
  TODO_324: 'Préparations à base de farine pour pâtisserie',
  TODO_325: 'Purée/coulis de tomates (100% tomates)',
  TODO_326: 'Pâtes (teneur en eau ~ 12%)',
  TODO_327: 'Pâtes sêches',
  TODO_328: 'Pâtes à tarte/pizza et pain réfrigérées',
  TODO_329: 'Pâtes à tarte/pizza et pain surgelées',
  TODO_330: 'Pêches/nectarines',
  TODO_331: 'Raisin de table',
  TODO_332: 'Rein',
  TODO_333: 'Rein + graisse périrénale',
  TODO_334: 'Riz',
  TODO_335: 'Riz (en grains, non transformé, non étuvé)',
  TODO_336: 'Riz (hors plats préparés)',
  TODO_337: 'Riz camargue',
  TODO_338: 'Riz et produits à base de riz',
  TODO_339: 'Salades 4ième gamme',
  TODO_340: 'Salades conditionnées en pet recyclés',
  TODO_341: 'Salades de légumes',
  TODO_342: 'Sandwichs sans viande',
  TODO_343: 'Sang',
  TODO_344: 'Sarrasin non cuit (en grains)',
  TODO_345: 'Sauce de soja',
  TODO_346: 'Saucissons secs',
  TODO_347: 'Saumons et truites fumés',
  TODO_348: 'Seigle (en grains, ou sous forme de farine complète)',
  TODO_349: 'Seigle (grains) non cuit',
  TODO_350: 'Seigle non cuit (en grains)',
  TODO_351: 'Sels',
  TODO_352: 'Snacks : biscuits apéritifs (ex : crackers, bretzels, minizzas)',
  TODO_353: 'Sorgho (grains) non cuit',
  TODO_354: 'Sorgho non cuit (en grains)',
  TODO_355: 'Soupes',
  TODO_356: 'Sous-produits de meunerie matières premières végétales',
  TODO_357: 'Substituts produits carnés',
  TODO_358: 'Substituts produits de la pêche',
  TODO_359: 'Substituts produits laitiers',
  TODO_360: 'Tartinables végétaux',
  TODO_361: 'Thon',
  TODO_362: 'Thyroïde',
  TODO_363: 'Thé',
  TODO_364: 'Thés',
  TODO_365: 'Tomates',
  TODO_366: 'Tourteaux',
  TODO_367: 'Tourteaux non ogm',
  TODO_368: 'Tubercules',
  TODO_369:
    'Tubercules (ex :pomme de terre, patate douce, manioc, topinambour, igname)',
  TODO_370: 'Urine',
  TODO_371: 'Urine+poil',
  TODO_372: 'Viande',
  TODO_373: 'Viande fraîche de boeuf poulet',
  TODO_374: 'Viande fraîche de porc dinde',
  TODO_375: 'Viandes fumées',
  TODO_376: 'Viandes traitées thermiquement',
  TODO_377: 'Vinaigrettes, sauces salades',
  TODO_378: 'Volaille - autre volaille : muscle',
  TODO_379: 'Volaille - autre volaille : muscle+foie',
  TODO_380: 'Volaille - dinde : muscle',
  TODO_381: 'Volaille - dinde : muscle+foie',
  TODO_382: 'Volaille - poule de réforme : muscle',
  TODO_383: 'Volaille - poule de réforme : muscle+foie',
  TODO_384: 'Volaille - poulet de chair : muscle',
  TODO_385: 'Volaille - poulet de chair : muscle+foie',
  TODO_386: 'Épeautre (grains) non cuit',
  TODO_387: 'Épeautre non cuit (en grains)',
  TODO_388: 'Épices boutons (ex: clou de girofle)',
  TODO_389: 'Épices en graines (ex: muscade, fenugrec, anis)',
  TODO_390: 'Épices et herbes séchées',
  TODO_391: 'Épices-fruits (ex : poivre, vanille, piment,cardamone)',
  TODO_392: 'Épices-racines ou rhizome (ex : curcuma, gingembre, galanga)',
  TODO_393: 'Épices-écorces (ex: cannelle)',
  TODO_394: 'Équin : graisse périrénale',
  TODO_395: 'Équin : muscle',
  TODO_396: 'Œuf caille',
  TODO_397: 'Œuf de caille',
  TODO_398: 'Œuf de poule',
  TODO_399: 'Œuf poule'
} as const satisfies Record<Matrix, string>;
