import { z } from 'zod';
import { MatrixDeprecated } from './Matrix';
import { MatrixLabels } from './MatrixLabels';

export const MatrixKindEffective = z.enum([
  'A00GY',
  'A00RT',
  'A00JD',
  'A04JS',
  'A001M',
  'A00FN',
  'A010V',
  'A03NJ',
  'A00TQ',
  'A00FX',
  'A015M',
  'A00JN',
  'A00LD',
  'A04MA',
  'A01EA',
  'A012B',
  'A00PX',
  'A01JT',
  'A042C',
  'A00KE',
  'A01BQ',
  'A01DT',
  'A0DQS',
  'A00HZ',
  'A01DV',
  'A001D',
  'A000L',
  'A00HQ',
  'A01QX',
  'A01RJ',
  'A01RL',
  'A01RG',
  'A01SN',
  'A031E',
  'A00DN',
  'A00SF',
  'A002C',
  'A0CYE',
  'A00VE',
  'A04QY',
  'A0DKQ',
  'A04KS',
  'A010B',
  'A0DCV',
  'A01GP',
  'A0DBR',
  'A0CGY',
  'A015S',
  'A01HP',
  'A01GL',
  'A04JV',
  'A00ZY',
  'A00LM',
  'A0DQE',
  'A0DQP',
  'A04KA',
  'A0CGX',
  'A00JH',
  'A0CGV',
  'A0CGZ',
  'A00VA',
  'A0DNV',
  'A004H',
  'A0C0Z',
  'A0D9Q',
  'A0DPQ',
  'A0DKP',
  'A0DVX',
  'A0DLQ',
  'A0ETN',
  'A000Y',
  'A0D9R',
  'A0DBQ',
  'A00VB',
  'A00ZT',
  'A0DQF',
  'A0DEQ',
  'A0DEH',
  'A0DLC',
  'A012N',
  'A042B',
  'A00QT',
  'A01LN',
  'A000S',
  'A00QD',
  'A0DQC',
  'A003J',
  'A00EF',
  'A0DBP',
  'A0DPB',
  'A011Y',
  'A0DEN',
  'A01BT',
  'A01DH',
  'A0CXQ',
  'A0DRB',
  'A00VP',
  'A0DQT',
  'A04HC',
  'A0DPV',
  'A04JZ',
  'A0DLV',
  'A0CYJ',
  'A04JX',
  'A003X',
  'A00TJ',
  'A00MH',
  'A015N',
  'A01LE',
  'A00GL',
  'A0DPR',
  'A00VK',
  'A04JP',
  'TODO_1',
  'TODO_2',
  'TODO_3',
  'TODO_4',
  'TODO_5',
  'TODO_6',
  'TODO_7',
  'TODO_8',
  'TODO_9',
  'TODO_10',
  'TODO_11',
  'TODO_12',
  'TODO_13',
  'TODO_14',
  'TODO_15',
  'TODO_16',
  'TODO_17',
  'TODO_18',
  'TODO_19',
  'TODO_20',
  'TODO_21',
  'TODO_22',
  'TODO_23',
  'TODO_24',
  'TODO_25',
  'TODO_26',
  'TODO_27',
  'TODO_28',
  'TODO_29',
  'TODO_30',
  'TODO_31',
  'TODO_32',
  'TODO_33',
  'TODO_34',
  'TODO_35',
  'TODO_36',
  'TODO_37',
  'TODO_38',
  'TODO_39',
  'TODO_40',
  'TODO_41',
  'TODO_42',
  'TODO_43',
  'TODO_44',
  'TODO_45',
  'TODO_46',
  'TODO_47',
  'TODO_48',
  'TODO_49',
  'TODO_50',
  'TODO_51',
  'TODO_52',
  'TODO_53',
  'TODO_54',
  'TODO_55',
  'TODO_56',
  'TODO_57',
  'TODO_58',
  'TODO_59',
  'TODO_60',
  'TODO_61',
  'TODO_62',
  'TODO_63',
  'TODO_64',
  'TODO_65',
  'TODO_66',
  'TODO_67',
  'TODO_68',
  'TODO_69',
  'TODO_70',
  'TODO_71',
  'TODO_72',
  'TODO_73',
  'TODO_74',
  'TODO_75',
  'TODO_76',
  'TODO_77',
  'TODO_78',
  'TODO_79',
  'TODO_80',
  'TODO_81',
  'TODO_82',
  'TODO_83',
  'TODO_84',
  'TODO_85',
  'TODO_86',
  'TODO_87',
  'TODO_88',
  'TODO_89',
  'TODO_90',
  'TODO_91',
  'TODO_92',
  'TODO_93',
  'TODO_94',
  'TODO_95',
  'TODO_96',
  'TODO_97',
  'TODO_98',
  'TODO_99',
  'TODO_100',
  'TODO_101',
  'TODO_102',
  'TODO_103',
  'TODO_104',
  'TODO_105',
  'TODO_106',
  'TODO_107',
  'TODO_108',
  'TODO_109',
  'TODO_110',
  'TODO_111',
  'TODO_112',
  'TODO_113',
  'TODO_114',
  'TODO_115',
  'TODO_116',
  'TODO_117',
  'TODO_118',
  'TODO_119',
  'TODO_120',
  'TODO_121',
  'TODO_122',
  'TODO_123',
  'TODO_124',
  'TODO_125',
  'TODO_126',
  'TODO_127',
  'TODO_128',
  'TODO_129',
  'TODO_130',
  'TODO_131',
  'TODO_132',
  'TODO_133',
  'TODO_134',
  'TODO_135',
  'TODO_136',
  'TODO_137',
  'TODO_138',
  'TODO_139',
  'TODO_140',
  'TODO_141',
  'TODO_142',
  'TODO_143',
  'TODO_144',
  'TODO_145',
  'TODO_146',
  'TODO_147',
  'TODO_148',
  'TODO_149',
  'TODO_150',
  'TODO_151',
  'TODO_152',
  'TODO_153',
  'TODO_154',
  'TODO_155',
  'TODO_156',
  'TODO_157',
  'TODO_158',
  'TODO_159',
  'TODO_160',
  'TODO_161',
  'TODO_162',
  'TODO_163',
  'TODO_164',
  'TODO_165',
  'TODO_166',
  'TODO_167',
  'TODO_168',
  'TODO_169',
  'TODO_170',
  'TODO_171',
  'TODO_172',
  'TODO_173',
  'TODO_174',
  'TODO_175',
  'TODO_176',
  'TODO_177',
  'TODO_178',
  'TODO_179',
  'TODO_180',
  'TODO_181',
  'TODO_182',
  'TODO_183',
  'TODO_184',
  'TODO_185',
  'TODO_186',
  'TODO_187',
  'TODO_188',
  'TODO_189',
  'TODO_190',
  'TODO_191',
  'TODO_192',
  'TODO_193',
  'TODO_194',
  'TODO_195',
  'TODO_196',
  'TODO_197',
  'TODO_198',
  'TODO_199',
  'TODO_200',
  'TODO_201',
  'TODO_202',
  'TODO_203',
  'TODO_204',
  'TODO_205',
  'TODO_206',
  'TODO_207',
  'TODO_208',
  'TODO_209',
  'TODO_210',
  'TODO_211',
  'TODO_212',
  'TODO_213',
  'TODO_214',
  'TODO_215',
  'TODO_216',
  'TODO_217',
  'TODO_218',
  'TODO_219',
  'TODO_220',
  'TODO_221',
  'TODO_222',
  'TODO_223',
  'TODO_224',
  'TODO_225',
  'TODO_226',
  'TODO_227',
  'TODO_228',
  'TODO_229',
  'TODO_230',
  'TODO_231',
  'TODO_232',
  'TODO_233',
  'TODO_234',
  'TODO_235',
  'TODO_236',
  'TODO_237',
  'TODO_238',
  'TODO_239',
  'TODO_240',
  'TODO_241',
  'TODO_242',
  'TODO_243',
  'TODO_244',
  'TODO_245',
  'TODO_246',
  'TODO_247',
  'TODO_248',
  'TODO_249',
  'TODO_250',
  'TODO_251',
  'TODO_252',
  'TODO_253',
  'TODO_254',
  'TODO_255',
  'TODO_256',
  'TODO_257',
  'TODO_258',
  'TODO_259',
  'TODO_260',
  'TODO_261',
  'TODO_262',
  'TODO_263',
  'TODO_264',
  'TODO_265',
  'TODO_266',
  'TODO_267',
  'TODO_268',
  'TODO_269',
  'TODO_270',
  'TODO_271',
  'TODO_272',
  'TODO_273',
  'TODO_274',
  'TODO_275',
  'TODO_276',
  'TODO_277',
  'TODO_278',
  'TODO_279',
  'TODO_280',
  'TODO_281',
  'TODO_282',
  'TODO_283',
  'TODO_284',
  'TODO_285',
  'TODO_286',
  'TODO_287',
  'TODO_288',
  'TODO_289',
  'TODO_290',
  'TODO_291',
  'TODO_292',
  'TODO_293',
  'TODO_294',
  'TODO_295',
  'TODO_296',
  'TODO_297',
  'TODO_298',
  'TODO_299',
  'TODO_300',
  'TODO_301',
  'TODO_302',
  'TODO_303',
  'TODO_304',
  'TODO_305',
  'TODO_306',
  'TODO_307',
  'TODO_308',
  'TODO_309',
  'TODO_310',
  'TODO_311',
  'TODO_312',
  'TODO_313',
  'TODO_314',
  'TODO_315',
  'TODO_316',
  'TODO_317',
  'TODO_318',
  'TODO_319',
  'TODO_320',
  'TODO_321',
  'TODO_322',
  'TODO_323',
  'TODO_324',
  'TODO_325',
  'TODO_326',
  'TODO_327',
  'TODO_328',
  'TODO_329',
  'TODO_330',
  'TODO_331',
  'TODO_332',
  'TODO_333',
  'TODO_334',
  'TODO_335',
  'TODO_336',
  'TODO_337',
  'TODO_338',
  'TODO_339',
  'TODO_340',
  'TODO_341',
  'TODO_342',
  'TODO_343',
  'TODO_344',
  'TODO_345',
  'TODO_346',
  'TODO_347',
  'TODO_348',
  'TODO_349',
  'TODO_350',
  'TODO_351',
  'TODO_352',
  'TODO_353',
  'TODO_354',
  'TODO_355',
  'TODO_356',
  'TODO_357',
  'TODO_358',
  'TODO_359',
  'TODO_360',
  'TODO_361',
  'TODO_362',
  'TODO_363',
  'TODO_364',
  'TODO_365',
  'TODO_366',
  'TODO_367',
  'TODO_368',
  'TODO_369',
  'TODO_370',
  'TODO_371',
  'TODO_372',
  'TODO_373',
  'TODO_374',
  'TODO_375',
  'TODO_376',
  'TODO_377',
  'TODO_378',
  'TODO_379',
  'TODO_380',
  'TODO_381',
  'TODO_382',
  'TODO_383',
  'TODO_384',
  'TODO_385',
  'TODO_386',
  'TODO_387',
  'TODO_388',
  'TODO_389',
  'TODO_390',
  'TODO_391',
  'TODO_392',
  'TODO_393',
  'TODO_394',
  'TODO_395',
  'TODO_396',
  'TODO_397',
  'TODO_398',
  'TODO_399'
]);

export const OtherMatrixKind = z.literal('Other');

export const MatrixKind = z.enum(
  [...MatrixDeprecated.options, ...MatrixKindEffective.options],
  {
    error: () => 'Veuillez renseigner la catégorie de matrice programmée.'
  }
);

export type MatrixKind = z.infer<typeof MatrixKind>;
export type OtherMatrixKind = z.infer<typeof OtherMatrixKind>;

export const MatrixKindList: MatrixKind[] = MatrixKind.options;

const MatrixDeprecatedLabels: Record<MatrixDeprecated, string> =
  Object.fromEntries(
    MatrixDeprecated.options
      .map((key) => [key, MatrixLabels[key]])
      .filter(([_, value]) => value !== undefined)
  );

export const MatrixKindLabels: Record<MatrixKind | OtherMatrixKind, string> = {
  ...MatrixDeprecatedLabels,
  A00KR: 'Légumes-feuilles',
  A012R: 'Légumes secs (graines séchées de légumineuse)',
  A00GY: 'Aulx et échalotes',
  A00RT: 'Asperges',
  A00JD: 'Aubergines',
  A04JS: 'Bananes',
  A001M: 'Blé (froment)',
  A00FN: 'Brocolis',
  A010V: 'Canne à sucre',
  A03NJ: 'Cerises',
  A00TQ: 'Champignons de couche',
  A00FX: 'Choux pommés',
  A015M: 'Colza',
  A00JN: 'Cucurbitacés à peau comestible',
  A00LD: 'Endives',
  A04MA: 'Fines herbes',
  A01EA: 'Fraises',
  A012B: 'Haricots et pois écossés frais',
  A00PX: 'Haricots et pois non écossés frais',
  A01JT: 'Kiwis',
  A042C: 'Laitues et scaroles',
  A00KE: 'Melons',
  A01BQ: 'Olives',
  A01DT: 'Petits fruits',
  A0DQS: 'Pitaya / fruits du Dragon',
  A00HZ: 'Poivrons/Piments',
  A01DV: 'Raisins',
  A001D: 'Riz',
  A00HQ: 'Tomates',
  A01QX: 'Viande bovine',
  A01RJ: 'Viande ovine',
  A01RL: 'Viande caprine',
  A01RG: 'Viande porcine',
  A01SN: 'Viande de volaille',
  A031E: 'Œufs et ovoproduits',
  A015S: 'Graines de moutarde',
  A0DPQ: 'Corossols et similaires',
  A0DQF: 'Mangues et similaires',
  A01HP: 'Kakis et similaires',
  A0DLV: 'Potirons et similaires',
  A04JX: 'Racines de manioc et similaires',
  A00SF: 'Graines germées, pousses et similaires',
  A01GP: 'Prunes et similaires',
  A01LN: 'Goyaves et similaires',
  A0DVX: 'Abricots et similaires',
  A012N: 'Lupins (écossés)',
  A04JP: 'Litchis et similaires',
  A00QT: 'Radis et similaires',
  A01LE: 'Bananes plantains',
  A0DEQ: 'Céleris et similaires',
  A015N: 'Graines de navette',
  A0DPR: 'Durions et similaires',
  A0DBR: 'Graines de pavot et similaires',
  A0CGZ: 'Racines de curcuma et similaires',
  A003J: 'Farine de seigle',
  A0DEN: 'Artichauts et similaires',
  A0DBP: 'Graines de tournesol et similaires',
  A0DPB: 'Carottes et similaires',
  A04JV: "Fruits de l'arbre à pain et similaires",
  A0DCV: 'Mousses et lichens ',
  A042B: 'Salades et jeunes pousses',
  A01DH: 'Pommes et similaires',
  A0DPV: 'Ananas et similaires',
  A0DLQ: 'Pastèques et similaires',
  A0DBQ: 'Graines de sésame et similaires',
  A011Y: 'Graines fraîches de légumineuses (haricots, pois, etc.) ',
  A00EF: 'Flocons transformés à base de blé',
  A00ZY: 'Légumes-racines et tubercules tropicaux',
  A0DKP: 'Feuilles de moutarde brune et similaires',
  A00GL: 'Choux feuillus /verts et similaires',
  A00VA: 'Algues et organismes procaryotes',
  A0DQT: 'Figues de Barbarie et similaires',
  A0CXQ: 'Betteraves industrielles et potagères',
  A00TJ: 'Truffes',
  A00LM: 'Roquette et similaires',
  A00VK: 'Algue brune',
  A00DN: "Flocons transformés à base d'avoine",
  A0DQP: 'Avocats et similaires',
  A04HC: 'Autres légumineuses',
  A004H: "Farine d'épeautre",
  A0CGX: 'Racines de gingembre et similaires',
  A000L: 'Céréales à paille',
  A000Y: 'Millet commun et similaires',
  A04KA: 'Salsifis et similaires',
  A0CYE: 'Racines de réglisse et similaires',
  A0DNV: 'Topinambours et similaires',
  A04KS: 'Farines de céréales et de grains de type céréale',
  A0D9Q: 'Sorgho et similaires',
  A00QD: 'Lentilles fraîches',
  A00JH: 'Baie de goji',
  A010B: 'Taros',
  A00VP: 'Spiruline',
  A0DKQ: 'Cressons de terre et similaires',
  A002C: 'Son de céréales',
  A00ZT: 'Pommes de terre de consommation',
  A01GL: 'Pêches et similaires',
  A003X: 'Farine de blé',
  A00MH: 'Épinards et similaires',
  A0DQE: 'Papayes et similaires',
  A0ETN: 'Germes de céréales',
  A00VB: 'Algue verte',
  A0DQC: 'Grenades et similaires',
  A0CGV: 'Vanille et similaires',
  A04JZ: 'Raiforts et similaires',
  A00VE: 'Algue rouge',
  A0CGY: 'Racines de raifort et similaires',
  A0DEH: 'Poireaux et similaires',
  A04QY: 'Flocons de céréales et similaires',
  A0D9R: 'Seigle et similaires',
  A0DRB: 'Fruits de la passion et similaires',
  A000S: 'Maïs et similaires',
  A0C0Z: 'Maïs moulu',
  A0CYJ: 'Tamarin et similaires',
  A01BT: 'Agrumes',
  A0DLC: 'Mâche et similaires',
  TODO_1: 'Additif, prémélange',
  TODO_2: 'Algues',
  TODO_3: 'Algues, halophytes, aliments en contenant',
  TODO_4: 'Algues, halophytes, aliments en contenant - uniquement mp algues',
  TODO_5: 'Aliment',
  TODO_6: "Aliment (y compris aliment d'allaitement)",
  TODO_7: 'Aliment composé autre (lapin ou cheval)',
  TODO_8: 'Aliment composé autre (lapin)',
  TODO_9: 'Aliment composé petfood',
  TODO_10: 'Aliment composé petfood autre',
  TODO_11:
    'Aliment composé petfood autre - uniquement mélanges de graines pour oiseaux (graines entières)',
  TODO_12: 'Aliment composé petfood carnivore domestique',
  TODO_13:
    'Aliment composé petfood carnivores domestiques - aliments secs (croquettes) uniquement',
  TODO_14: 'Aliment composé poisson (aquaculture)',
  TODO_15: 'Aliment composé porcins',
  TODO_16: 'Aliment composé ruminants',
  TODO_17: 'Aliment composé veau, agneau, chevreau',
  TODO_18: 'Aliment composé volailles',
  TODO_19:
    "Aliment liquide (notamment d'allaitement) ou à défaut eau de boisson",
  TODO_20: 'Aliment liquide (ou à défaut eau de boisson)',
  TODO_21: 'Aliment médicamenteux',
  TODO_22: 'Aliments minéraux',
  TODO_23: 'Aliments pour bébés',
  TODO_24: 'Aliments pour bébés : compotes de pomme',
  TODO_25: 'Aliments pour bébés contenant de la pomme de terre',
  TODO_26:
    'Aliments pour bébés contenant des légumes-feuilles (cresson, endive, salades, blette, choux, épinard)',
  TODO_27:
    "Amandes d'abricots et les amandes non transformées entières, broyées, moulues ou concassées (mises sur le marché pour le consommateur final)",
  TODO_28: 'Amandes d’abricots, amandes, produits transformées à base d’amande',
  TODO_29: 'Ananas',
  TODO_30: 'Aubergines',
  TODO_31: 'Autres aliments composés (lapin, cheval, etc.)',
  TODO_32: 'Autres pièces cuites',
  TODO_33: 'Autres poissons fumés',
  TODO_34:
    'Autres produits et sous-produits végétaux ; produits de fermentation',
  TODO_35:
    'Autres produits et sous-produits végétaux ; produits de fermentation - herbes et plantes aromatiques uniquement',
  TODO_36: 'Avoine non cuit',
  TODO_37: 'Avoine non cuit (en grains)',
  TODO_38: 'Baies rouges fraîches',
  TODO_39: 'Baies rouges surgelées',
  TODO_40: 'Bananes',
  TODO_41: 'Blé (en grains, non transformé, non étuvé)',
  TODO_42: 'Blé dur non cuit',
  TODO_43: 'Blé dur non cuit (en grains)',
  TODO_44: 'Blé tendre non cuit',
  TODO_45: 'Blé tendre non cuit (en grains)',
  TODO_46: 'Boissons alcoolisées : bières',
  TODO_47: 'Boissons alcoolisées : cidres',
  TODO_48: 'Boissons alcoolisées : spiritueux',
  TODO_49: 'Boissons alcoolisées : spiritueux à base de pomme',
  TODO_50: 'Boissons alcoolisées : vins et produits similaires',
  TODO_51: 'Boissons conditionnées en pet recyclé',
  TODO_52: 'Bovin : graisse périrénale',
  TODO_53: 'Bovin : muscle+foie',
  TODO_54: 'Boyaux',
  TODO_55:
    'Brassicacées (ex : chou, chou chinois, chou-fleur, chou-kale, brocoli)',
  TODO_56: 'Brocolis',
  TODO_57: 'Cacao',
  TODO_58: 'Caecum',
  TODO_59: 'Cafés torréfiés (en grains, moulus, instantanés)',
  TODO_60: 'Caprin : graisse périrénale',
  TODO_61: 'Caprin : muscle+foie',
  TODO_62: 'Carottes',
  TODO_63: 'Céréales brutes',
  TODO_64: 'Céréales et produits dérivés, hors maïs',
  TODO_65:
    'Céréales et produits dérivés, hors maïs - graines entières (cibler sorgho, millet)',
  TODO_66:
    'Céréales et produits dérivés, hors maïs - graines entières céréales et dérivés',
  TODO_67:
    'Céréales pour petit-déjeuner et collations à base de céréales collation céréale',
  TODO_68:
    'Céréales pour petit-déjeuner et collations à base de céréales collations base',
  TODO_69:
    'Céréales pour petit-déjeuner et collations à base de céréales collations céréales',
  TODO_70: 'Céréales produites sur l’exploitation',
  TODO_71:
    "Céréales produites sur l’exploitation (céréales non broyées/non moulues pour l'ergot de seigle)",
  TODO_72: 'Chair',
  TODO_73: 'Chair + peau',
  TODO_74: 'Chair blanche',
  TODO_75: 'Champignons',
  TODO_76: 'Chicorée',
  TODO_77: 'Chips de banane',
  TODO_78: 'Chips de légumes (sauf pomme de terre)',
  TODO_79: 'Chips de pomme de terre',
  TODO_80: 'Chocolats au lait',
  TODO_81: 'Chocolats noirs',
  TODO_82: 'Choux fleurs',
  TODO_83: 'Clémentines/mandarines',
  TODO_84: 'Complément alimentaire',
  TODO_85: "Complément alimentaire à base d'huile de poisson",
  TODO_86: "Complément alimentaire à base d'huile poisson",
  TODO_87: 'Complément alimentaire à base de levure de riz rouge',
  TODO_88: 'Complément alimentaire à base de macro-algues séchées',
  TODO_89: 'Complément alimentaire à base de plantes séchées',
  TODO_90: 'Complément alimentaire à base de pollen',
  TODO_91: "Compléments alimentaires à base d'argile",
  TODO_92: 'Compléments alimentaires à base de levure de riz rouge',
  TODO_93: 'Compléments alimentaires à base de plantes séchées',
  TODO_94: 'Compléments alimentaires à base de pollen',
  TODO_95:
    'Compléments alimentaires contenant de la propolis, de la gelée royale ou de la spiruline',
  TODO_96:
    'Compléments alimentaires ou denrées susceptible de contenir des had',
  TODO_97: 'Compotes',
  TODO_98: 'Compotes de pomme',
  TODO_99: 'Concombres',
  TODO_100:
    'Confiserie, dragées, pâtisseries avec glaçage,- boissons en poudre, sirop de noix de coco...- sauce blanche de type « fast food », - produits alimentaires avec un colorant blanc/couleur pale importés des pays tiers',
  TODO_101: 'Confiseries',
  TODO_102: 'Confiseries à base de réglisse',
  TODO_103:
    'Confiseries,micro-confiseriesdestinées àrafraîchirl’haleine,gommes àmâcher, boissonscontenant de lamenthe ou de lamenthe poivrée',
  TODO_104: 'Courgettes',
  TODO_105: 'Crackers de riz',
  TODO_106: 'Crevettes',
  TODO_107: 'Crevettes cuites',
  TODO_108: 'Cumin et herbes séchées',
  TODO_109: 'Daoa / daov',
  TODO_110: "Daov d'origine hors fr",
  TODO_111: 'Denrées alimentaires déshydratées déclassées',
  TODO_112: 'Denrées susceptibles de contenir des substances médicamenteuses',
  TODO_113: 'Denrées transformés boissons',
  TODO_114: "Drêches directement livrées à l'élevage",
  TODO_115: 'Eau boisson',
  TODO_116: 'Eau de mer',
  TODO_117: 'Ensilage',
  TODO_118: 'Épeautre (grains) non cuit',
  TODO_119: 'Épeautre non cuit (en grains)',
  TODO_120: 'Épices boutons (ex: clou de girofle)',
  TODO_121: 'Épices en graines (ex: muscade, fenugrec, anis)',
  TODO_122: 'Épices et herbes séchées',
  TODO_123: 'Épices-écorces (ex: cannelle)',
  TODO_124: 'Épices-fruits (ex : poivre, vanille, piment,cardamone)',
  TODO_125: 'Épices-racines ou rhizome (ex : curcuma, gingembre, galanga)',
  TODO_126: 'Epinards',
  TODO_127: 'Équin : graisse périrénale',
  TODO_128: 'Équin : muscle',
  TODO_129: 'Farine de poisson',
  TODO_130: 'Farine de sang ou produits sanguins',
  TODO_131: 'Farines blanches autres que de blé et farines complètes',
  TODO_132: 'Farines de blé blanches',
  TODO_133: 'Fèces',
  TODO_134:
    'Fines herbes (ex : basilic, sauge, thym, menthe, laurier, origan, estragon, aneth)',
  TODO_135:
    'Fines herbes fraiches, non déshydratées (ex : basilic, ciboulette, sauge, thym, menthe, laurier, origan, estragon, aneth)',
  TODO_136: 'Foie',
  TODO_137: 'Foie (ou à défaut muscle)',
  TODO_138: 'Foie ou muscle',
  TODO_139: 'Fourrages',
  TODO_140: 'Fourrages déshydratés ( betterave,…)',
  TODO_141: 'Fourrages déshydratés (luzerne, betterave,...)',
  TODO_142: 'Fourrages ou ensilages',
  TODO_143: 'Fraises',
  TODO_144: 'Frites prêtes à consommer',
  TODO_145: 'Fromages à pâte dure',
  TODO_146: 'Fromages fumés',
  TODO_147: 'Fruit',
  TODO_148: 'Fruits à coque et dérivés (hors pistaches et amandes)',
  TODO_149: 'Fruits à coque et leurs dérivés',
  TODO_150: 'Fruits à coque et leurs dérivés primaires',
  TODO_151: 'Fruits à coque torréfiés',
  TODO_152: 'Fruits découpés',
  TODO_153: 'Fruits et légumes',
  TODO_154: 'Fruits et leurs dérivés en conserve',
  TODO_155: 'Fruits frais',
  TODO_156: 'Fruits frais ou congelés',
  TODO_157: 'Fruits rouges(hors fraises et cerises)',
  TODO_158: 'Fruits séchés',
  TODO_159: 'Gélatine',
  TODO_160: 'Gélule avec colorant blanc',
  TODO_161: 'Gibier',
  TODO_162: 'Gibier d’élevage : muscle',
  TODO_163: 'Gibier d’élevage : muscle + foie',
  TODO_164: 'Gonades',
  TODO_165: 'Graines de chanvre',
  TODO_166: 'Graines de chanvre ou de tournesol',
  TODO_167: 'Graines de lin',
  TODO_168: 'Graines de lin, tourteaux de lin & aliments en contenant',
  TODO_169: 'Graines de pavot',
  TODO_170: 'Graines de tournesol',
  TODO_171: 'Graines et fruits oléagineux',
  TODO_172: 'Graines oléagineuses',
  TODO_173: 'Graines torréfiées',
  TODO_174: 'Graisse (+/- peau)',
  TODO_175: 'Graisse fondue',
  TODO_176: 'Graisse péri-rénale',
  TODO_177: 'Graisse périrénale',
  TODO_178: 'Graisse périrénale (à défaut rein+graisse périrénale)',
  TODO_179: 'Graisse périrénale ou muscle',
  TODO_180: 'Graisses et huiles animales et marines',
  TODO_181: 'Hareng',
  TODO_182: 'Haricots secs',
  TODO_183: 'Haricots verts',
  TODO_184: 'Huile de poisson',
  TODO_185: 'Huiles de poisson',
  TODO_186: 'Huiles et graisses végétales et leurs dérivés',
  TODO_187: 'Huiles issues de graines de chanvre',
  TODO_188: 'Huiles végétales (hors olives vierges)',
  TODO_189: 'Huiles végétales et dérivés (acides gras, etc.)',
  TODO_190: 'Huiles végétales non raffinées',
  TODO_191: 'Infusions à base de feuilles',
  TODO_192: 'Infusions à base de feuilles de chanvre',
  TODO_193: 'Infusions et ingrédients pour infusions',
  TODO_194: 'Jambons secs',
  TODO_195: 'Jus à base de raisin',
  TODO_196: "Jus d'orange (100% orange)",
  TODO_197: 'Jus de fruits, de légumes, nectars, boissons à base de plantes',
  TODO_198: 'Jus de pomme artisanal',
  TODO_199: 'Jus fruits/légumes',
  TODO_200: 'Kiwis',
  TODO_201: 'Lait cru de brebis',
  TODO_202: 'Lait cru de chèvre',
  TODO_203: 'Lait cru de vache',
  TODO_204: 'Lait cru entier',
  TODO_205: 'Lait de brebis cru',
  TODO_206: 'Lait de chèvre cru',
  TODO_207: 'Lait de vache cru',
  TODO_208: 'Laitues et autres salades',
  TODO_209: 'Langoustines',
  TODO_210: 'Lapin : muscle',
  TODO_211: 'Lapin : muscle + foie',
  TODO_212: 'Legume feuille',
  TODO_213: 'Légumes bulbes (ex : ail, oignon, ciboule, échalotte)',
  TODO_214: 'Légumes bulbes (ex : ciboulette, ail, oignon, ciboule, échalotte)',
  TODO_215: 'Légumes et leurs dérivés dans une conserve en métal',
  TODO_216:
    'Légumes feuilles (les endives ne peuvent être prélevées que si elles sont cultivées en pleine terre à l’extérieur et non sous abri)',
  TODO_217: 'Légumes feuilles frais',
  TODO_218: 'Légumes racinaires tubercule',
  TODO_219:
    'Légumes racines, tubercules tropicaux(ex: manioc, patate douce, christophine, taro, dachine)',
  TODO_220:
    'Légumes-feuilles (ex : artichaut, céleri, épinard, fenouil, endive, laitue, roquette, blette, choux)',
  TODO_221:
    'Légumes-feuilles (ex : épinard, endive, laitue, roquette, blette, choux)',
  TODO_222:
    'Légumes-fruits (ex : aubergine, avocat, citrouille, courge, piment,  poivron, potiron, tomate, concombre, olive)',
  TODO_223:
    'Légumes-fruits (ex : aubergine, citrouille, courge, piment doux,  poivron doux, potiron, tomate, concombre, melo, pastèque)',
  TODO_224:
    'Légumes-racines (ex : carotte, panais, betterave, navet, radis, céleri-rave, salsifis',
  TODO_225:
    'Légumes-tiges (ex : artichaut, céleris, asperge, cœur de palmier, fenouille, rhubarbe, poireau, pousses de bambou)',
  TODO_226:
    'Légumes-tiges (ex : cœur de palmier, fenouille, rhubarbe, poireau, pousses de bambou)',
  TODO_227: 'Légumineuses potagères',
  TODO_228: 'Légumineuses potagères fraiches (ex : haricots, pois, lentilles)',
  TODO_229: 'Légumineuses séchées et leurs dérivés primaires',
  TODO_230: 'Lentilles (sèches)',
  TODO_231: 'Lupins (secs) et similaires',
  TODO_232: 'Maïs (grains) non cuit',
  TODO_233: 'Maïs (hors fourrage) et produits dérivés',
  TODO_234: 'Maïs et produits dérivés',
  TODO_235: 'Maïs et produits dérivés - graines entières',
  TODO_236: 'Maïs non cuit (en grains)',
  TODO_237: 'Maïs ou blé grains',
  TODO_238: 'Mangues',
  TODO_239: "Matière première d'origine minérale",
  TODO_240:
    "Matière première d'origine minérale directement livrées en élevage",
  TODO_241:
    'Matrices recommandées:avocatsbananes plantincéleriscerisescitrons vertscressonsfeuilles de vignefiguesfruits de la passion/maracujasgoyavesgrenadesherbes aromatiques fraichespimentspitaya (fruit du dragon)pois (non écossés)/ pois chiche',
  TODO_242: 'Melons',
  TODO_243: 'Miel',
  TODO_244: "Miel (hors miel d'arbre)",
  TODO_245: 'Millet (grains) non cuit',
  TODO_246: 'Millet non cuit (en grains)',
  TODO_247: 'Mollusques bivalves',
  TODO_248: 'Moutardes',
  TODO_249: 'Mouture (farine) de blé dur',
  TODO_250: 'Mouture (farine) de blé tendre',
  TODO_251: 'Muscle',
  TODO_252: 'Muscle ou foie',
  TODO_253: 'Muscle+foie',
  TODO_254: 'Nougats, massepain',
  TODO_255: 'Oeil (rétine)+poumon',
  TODO_256: 'Œuf caille',
  TODO_257: 'Œuf de caille',
  TODO_258: 'Œuf de poule',
  TODO_259: 'Œuf poule',
  TODO_260: 'Oignons',
  TODO_261:
    'Oléagineux, protéagineux (tourteaux, etc.) - graines entières (cibler tournesol, soja)',
  TODO_262: 'Oléagineux, protéagineux et produits dérivés (tourteaux, etc.)',
  TODO_263:
    'Oléagineux, protéagineux et produits dérivés (tourteaux, etc.) - colza uniquement',
  TODO_264:
    'Oléagineux, protéagineux et produits dérivés (tourteaux, etc.) - hors soja',
  TODO_265: 'Oranges',
  TODO_266: 'Orge (grains) non cuit',
  TODO_267: 'Orge non cuit (en grains)',
  TODO_268: 'Ovin : graisse périrénale',
  TODO_269: 'Ovin : muscle+foie',
  TODO_270: 'Ovoproduits/produits laitiers',
  TODO_271: 'Pain',
  TODO_272: 'Pat d’insectes',
  TODO_273: "Pat de porcs, volaille ou insectes destinées à l'aquaculture",
  TODO_274: 'Pat porc, volailles, insecte',
  TODO_275: 'Pat porcs, volailles, insectes, ruminants',
  TODO_276: 'Pâtes (teneur en eau ~ 12%)',
  TODO_277: 'Pâtes à tarte/pizza et pain réfrigérées',
  TODO_278: 'Pâtes à tarte/pizza et pain surgelées',
  TODO_279: 'Pâtes sêches',
  TODO_280: 'Pêches/nectarines',
  TODO_281: 'Pistaches',
  TODO_282: 'Plante aromatique',
  TODO_283: 'Plats pour personnes âgées',
  TODO_284: 'Poil',
  TODO_285: 'Poireaux',
  TODO_286: 'Poires',
  TODO_287: 'Pommes',
  TODO_288: 'Pommes de terre',
  TODO_289: 'Pommes de terre fraîches',
  TODO_290: 'Porcin : graisse périrénale',
  TODO_291: 'Porcin : muscle+foie',
  TODO_292: 'Poudre de cacao non sucrée',
  TODO_293: 'Poumon',
  TODO_294: "Prémélange d'additifs",
  TODO_295:
    'Préparation pour nourrisson et enfants en bas âge à base de céréales',
  TODO_296: 'Préparations à base de céréales pour nourrissons',
  TODO_297:
    'Préparations à base de céréales pour nourrissons (conserve en métal)',
  TODO_298:
    'Préparations à base de céréales pour nourrissons à base de maïs, sorgho, millet ou sarrasin',
  TODO_299: 'Préparations à base de farine pour pâtisserie',
  TODO_300:
    'Préparations pour enfants en bas âge - aliments pour bébés (petits pots de fruits ou légumes sans viande ni poisson)',
  TODO_301:
    'Préparations pour enfants en bas âge - laits infantiles 1er et 2ème âge',
  TODO_302:
    'Préparations pour enfants en bas âge - préparations à base de céréales',
  TODO_303:
    'Préparations pour nourrissons, de suite ou pour enfants en bas âge',
  TODO_304:
    "Préparations pour nourrissons, de suite ou pour enfants en bas âge - laits infantiles - (liquide prêt à l'emploi)",
  TODO_305:
    'Préparations pour nourrissons, de suite ou pour enfants en bas âge - laits infantiles - (poudre / conserve en métal)',
  TODO_306: 'Produit de la pêche - céphalopode : chair',
  TODO_307: 'Produit de la pêche - crustacé : chair',
  TODO_308: 'Produit de la pêche - mollusque : chair',
  TODO_309:
    "Produit de la pêche - poisson d'aquaculture eau douce ou eau de mer : chair",
  TODO_310:
    "Produit de la pêche - poisson d'eau douce sauvage ou élevage : chair",
  TODO_311: 'Produit de la pêche - poisson de mer sauvage ou élevage : chair',
  TODO_312: 'Produits à base de graines',
  TODO_313: 'Produits à base de sarrasin, millet ou maïs',
  TODO_314: 'Produits à cuire',
  TODO_315: 'Produits à poêler réfrigérés',
  TODO_316: 'Produits à poêler surgelés',
  TODO_317: 'Produits contenant des graines de pavot',
  TODO_318: 'Produits de boulangerie : beignets, churros (minimum 5% mg)',
  TODO_319: 'Produits de boulangerie : beignets, crackers, biscottes',
  TODO_320: 'Produits de boulangerie : pains',
  TODO_321: 'Produits de boulangerie : pains, beignets, crackers, biscottes',
  TODO_322: 'Produits de boulangerie fine : biscuits, gâteaux, viennoiseries',
  TODO_323:
    'Produits de boulangerie fine : biscuits, gâteaux, viennoiseries, beignets, crackers, biscottes',
  TODO_324: 'Produits de boulangerie fine : viennoiseries',
  TODO_325:
    'Produits de céréales et de boulangerie (farine de céréales, pains)',
  TODO_326: 'Produits de charcuterie',
  TODO_327: 'Produits de la pêche fumés',
  TODO_328: "Produits de mouture d'avoine",
  TODO_329: "Produits de mouture d'épeautre",
  TODO_330: "Produits de mouture d'orge",
  TODO_331: 'Produits de mouture de blé dur',
  TODO_332: 'Produits de mouture de blé tendre',
  TODO_333: 'Produits de mouture de maïs',
  TODO_334: 'Produits de mouture de millet',
  TODO_335: 'Produits de mouture de sarrasin',
  TODO_336: 'Produits de mouture de seigle',
  TODO_337: 'Produits de mouture de sorgho',
  TODO_338: 'Produits dérivés de la tomate',
  TODO_339: 'Produits sucrés',
  TODO_340:
    'Produits suivants « sans sucre » ou « allégé » : confiseries, boissons, confitures, desserts, pâtes à tartiner',
  TODO_341:
    'Produits suivants contenant de la réglisse :bonbons, boissons anisées, infusions, glaces',
  TODO_342:
    'Produits suivants présentant une coloration jaune-orangé : confiseries et produits sucrés,boissonsyaourts et glaces aromatisés, confitures,charcuteries (saucisses, chorizo), poissons fumés,glaçages, crèmes',
  TODO_343:
    'Produits suivants présentant une coloration rouge : confiseries et produits sucrés,boissonsyaourts et glaces aromatisés, confitures,charcuteries (saucisses, chorizo),glaçages, crèmes',
  TODO_344: 'Purée/coulis de tomates (100% tomates)',
  TODO_345: 'Raisin de table',
  TODO_346: 'Rein',
  TODO_347: 'Rein + graisse périrénale',
  TODO_348: 'Riz',
  TODO_349: 'Riz (en grains, non transformé, non étuvé)',
  TODO_350: 'Riz (hors plats préparés)',
  TODO_351: 'Riz camargue',
  TODO_352: 'Riz et produits à base de riz',
  TODO_353: 'Salades 4ième gamme',
  TODO_354: 'Salades conditionnées en pet recyclés',
  TODO_355: 'Salades de légumes',
  TODO_356: 'Sandwichs sans viande',
  TODO_357: 'Sang',
  TODO_358: 'Sarrasin non cuit (en grains)',
  TODO_359: 'Sauce de soja',
  TODO_360: 'Saucissons secs',
  TODO_361: 'Saumons et truites fumés',
  TODO_362: 'Seigle (en grains, ou sous forme de farine complète)',
  TODO_363: 'Seigle (grains) non cuit',
  TODO_364: 'Seigle non cuit (en grains)',
  TODO_365: 'Sels',
  TODO_366: 'Snacks : biscuits apéritifs (ex : crackers, bretzels, minizzas)',
  TODO_367: 'Sorgho (grains) non cuit',
  TODO_368: 'Sorgho non cuit (en grains)',
  TODO_369: 'Soupes',
  TODO_370: 'Sous-produits de meunerie matières premières végétales',
  TODO_371: 'Substituts produits carnés',
  TODO_372: 'Substituts produits de la pêche',
  TODO_373: 'Substituts produits laitiers',
  TODO_374: 'Tartinables végétaux',
  TODO_375: 'Thé',
  TODO_376: 'Thés',
  TODO_377: 'Thon',
  TODO_378: 'Thyroïde',
  TODO_379: 'Tomates',
  TODO_380: 'Tourteaux',
  TODO_381: 'Tourteaux non ogm',
  TODO_382: 'Tubercules',
  TODO_383:
    'Tubercules (ex :pomme de terre, patate douce, manioc, topinambour, igname)',
  TODO_384: 'Urine',
  TODO_385: 'Urine+poil',
  TODO_386: 'Viande',
  TODO_387: 'Viande fraîche de boeuf poulet',
  TODO_388: 'Viande fraîche de porc dinde',
  TODO_389: 'Viandes fumées',
  TODO_390: 'Viandes traitées thermiquement',
  TODO_391: 'Vinaigrettes, sauces salades',
  TODO_392: 'Volaille - autre volaille : muscle',
  TODO_393: 'Volaille - autre volaille : muscle+foie',
  TODO_394: 'Volaille - dinde : muscle',
  TODO_395: 'Volaille - dinde : muscle+foie',
  TODO_396: 'Volaille - poule de réforme : muscle',
  TODO_397: 'Volaille - poule de réforme : muscle+foie',
  TODO_398: 'Volaille - poulet de chair : muscle',
  TODO_399: 'Volaille - poulet de chair : muscle+foie',
  Other: 'Autre'
};
