import { z } from 'zod';
import { MatrixDeprecated } from './Matrix';
import { MatrixLabels } from './MatrixLabels';

export const MatrixKindEffective = z.enum([
  'A00GY',
  'A00RT',
  'A00JD',
  'A04JS',
  'A001M',
  'A00FN',
  'A010V',
  'A03NJ',
  'A00TQ',
  'A00FX',
  'A015M',
  'A00JN',
  'A00LD',
  'A04MA',
  'A01EA',
  'A012B',
  'A00PX',
  'A01JT',
  'A042C',
  'A00KE',
  'A01BQ',
  'A01DT',
  'A0DQS',
  'A00HZ',
  'A01DV',
  'A001D',
  'A000L',
  'A00HQ',
  'A01QX',
  'A01RJ',
  'A01RL',
  'A01RG',
  'A01SN',
  'A031E',
  'A00DN',
  'A00SF',
  'A002C',
  'A0CYE',
  'A00VE',
  'A04QY',
  'A0DKQ',
  'A04KS',
  'A010B',
  'A0DCV',
  'A01GP',
  'A0DBR',
  'A0CGY',
  'A015S',
  'A01HP',
  'A01GL',
  'A04JV',
  'A00ZY',
  'A00LM',
  'A0DQE',
  'A0DQP',
  'A04KA',
  'A0CGX',
  'A00JH',
  'A0CGV',
  'A0CGZ',
  'A00VA',
  'A0DNV',
  'A004H',
  'A0C0Z',
  'A0D9Q',
  'A0DPQ',
  'A0DKP',
  'A0DVX',
  'A0DLQ',
  'A0ETN',
  'A000Y',
  'A0D9R',
  'A0DBQ',
  'A00VB',
  'A00ZT',
  'A0DQF',
  'A0DEQ',
  'A0DEH',
  'A0DLC',
  'A012N',
  'A042B',
  'A00QT',
  'A01LN',
  'A000S',
  'A00QD',
  'A0DQC',
  'A003J',
  'A00EF',
  'A0DBP',
  'A0DPB',
  'A011Y',
  'A0DEN',
  'A01BT',
  'A01DH',
  'A0CXQ',
  'A0DRB',
  'A00VP',
  'A0DQT',
  'A04HC',
  'A0DPV',
  'A04JZ',
  'A0DLV',
  'A0CYJ',
  'A04JX',
  'A003X',
  'A00TJ',
  'A00MH',
  'A015N',
  'A01LE',
  'A00GL',
  'A0DPR',
  'A00VK',
  'A04JP'
]);

export const OtherMatrixKind = z.literal('Other');

export const MatrixKind = z.enum(
  [...MatrixDeprecated.options, ...MatrixKindEffective.options],
  {
    error: () => 'Veuillez renseigner la catégorie de matrice programmée.'
  }
);

export type MatrixKind = z.infer<typeof MatrixKind>;
export type OtherMatrixKind = z.infer<typeof OtherMatrixKind>;

export const MatrixKindList: MatrixKind[] = MatrixKind.options;

const MatrixDeprecatedLabels: Record<MatrixDeprecated, string> =
  Object.fromEntries(
    MatrixDeprecated.options
      .map((key) => [key, MatrixLabels[key]])
      .filter(([_, value]) => value !== undefined)
  );

export const MatrixKindLabels: Record<MatrixKind | OtherMatrixKind, string> = {
  ...MatrixDeprecatedLabels,
  A00KR: 'Légumes-feuilles',
  A012R: 'Légumes secs (graines séchées de légumineuse)',
  A00GY: 'Aulx et échalotes',
  A00RT: 'Asperges',
  A00JD: 'Aubergines',
  A04JS: 'Bananes',
  A001M: 'Blé (froment)',
  A00FN: 'Brocolis',
  A010V: 'Canne à sucre',
  A03NJ: 'Cerises',
  A00TQ: 'Champignons de couche',
  A00FX: 'Choux pommés',
  A015M: 'Colza',
  A00JN: 'Cucurbitacés à peau comestible',
  A00LD: 'Endives',
  A04MA: 'Fines herbes',
  A01EA: 'Fraises',
  A012B: 'Haricots et pois écossés frais',
  A00PX: 'Haricots et pois non écossés frais',
  A01JT: 'Kiwis',
  A042C: 'Laitues et scaroles',
  A00KE: 'Melons',
  A01BQ: 'Olives',
  A01DT: 'Petits fruits',
  A0DQS: 'Pitaya / fruits du Dragon',
  A00HZ: 'Poivrons/Piments',
  A01DV: 'Raisins',
  A001D: 'Riz',
  A00HQ: 'Tomates',
  A01QX: 'Viande bovine',
  A01RJ: 'Viande ovine',
  A01RL: 'Viande caprine',
  A01RG: 'Viande porcine',
  A01SN: 'Viande de volaille',
  A031E: 'Œufs et ovoproduits',
  A015S: 'Graines de moutarde',
  A0DPQ: 'Corossols et similaires',
  A0DQF: 'Mangues et similaires',
  A01HP: 'Kakis et similaires',
  A0DLV: 'Potirons et similaires',
  A04JX: 'Racines de manioc et similaires',
  A00SF: 'Graines germées, pousses et similaires',
  A01GP: 'Prunes et similaires',
  A01LN: 'Goyaves et similaires',
  A0DVX: 'Abricots et similaires',
  A012N: 'Lupins (écossés)',
  A04JP: 'Litchis et similaires',
  A00QT: 'Radis et similaires',
  A01LE: 'Bananes plantains',
  A0DEQ: 'Céleris et similaires',
  A015N: 'Graines de navette',
  A0DPR: 'Durions et similaires',
  A0DBR: 'Graines de pavot et similaires',
  A0CGZ: 'Racines de curcuma et similaires',
  A003J: 'Farine de seigle',
  A0DEN: 'Artichauts et similaires',
  A0DBP: 'Graines de tournesol et similaires',
  A0DPB: 'Carottes et similaires',
  A04JV: "Fruits de l'arbre à pain et similaires",
  A0DCV: 'Mousses et lichens ',
  A042B: 'Salades et jeunes pousses',
  A01DH: 'Pommes et similaires',
  A0DPV: 'Ananas et similaires',
  A0DLQ: 'Pastèques et similaires',
  A0DBQ: 'Graines de sésame et similaires',
  A011Y: 'Graines fraîches de légumineuses (haricots, pois, etc.) ',
  A00EF: 'Flocons transformés à base de blé',
  A00ZY: 'Légumes-racines et tubercules tropicaux',
  A0DKP: 'Feuilles de moutarde brune et similaires',
  A00GL: 'Choux feuillus /verts et similaires',
  A00VA: 'Algues et organismes procaryotes',
  A0DQT: 'Figues de Barbarie et similaires',
  A0CXQ: 'Betteraves industrielles et potagères',
  A00TJ: 'Truffes',
  A00LM: 'Roquette et similaires',
  A00VK: 'Algue brune',
  A00DN: "Flocons transformés à base d'avoine",
  A0DQP: 'Avocats et similaires',
  A04HC: 'Autres légumineuses',
  A004H: "Farine d'épeautre",
  A0CGX: 'Racines de gingembre et similaires',
  A000L: 'Céréales à paille',
  A000Y: 'Millet commun et similaires',
  A04KA: 'Salsifis et similaires',
  A0CYE: 'Racines de réglisse et similaires',
  A0DNV: 'Topinambours et similaires',
  A04KS: 'Farines de céréales et de grains de type céréale',
  A0D9Q: 'Sorgho et similaires',
  A00QD: 'Lentilles fraîches',
  A00JH: 'Baie de goji',
  A010B: 'Taros',
  A00VP: 'Spiruline',
  A0DKQ: 'Cressons de terre et similaires',
  A002C: 'Son de céréales',
  A00ZT: 'Pommes de terre de consommation',
  A01GL: 'Pêches et similaires',
  A003X: 'Farine de blé',
  A00MH: 'Épinards et similaires',
  A0DQE: 'Papayes et similaires',
  A0ETN: 'Germes de céréales',
  A00VB: 'Algue verte',
  A0DQC: 'Grenades et similaires',
  A0CGV: 'Vanille et similaires',
  A04JZ: 'Raiforts et similaires',
  A00VE: 'Algue rouge',
  A0CGY: 'Racines de raifort et similaires',
  A0DEH: 'Poireaux et similaires',
  A04QY: 'Flocons de céréales et similaires',
  A0D9R: 'Seigle et similaires',
  A0DRB: 'Fruits de la passion et similaires',
  A000S: 'Maïs et similaires',
  A0C0Z: 'Maïs moulu',
  A0CYJ: 'Tamarin et similaires',
  A01BT: 'Agrumes',
  A0DLC: 'Mâche et similaires',
  Other: 'Autre'
};
