archi:
	cat architecture.puml | docker run --rm -i -e JAVA_TOOL_OPTIONS="-Dfile.encoding=UTF-8" agileek/plantuml:1.2022.3 > architecture.svg
dai-flow:
	cat dai-flow.puml | docker run --rm -i -e JAVA_TOOL_OPTIONS="-Dfile.encoding=UTF-8" agileek/plantuml:1.2022.3 > dai-flow.svg
dai-flow-module-labo:
	cat dai-flow-module-labo.puml | docker run --rm -i -e JAVA_TOOL_OPTIONS="-Dfile.encoding=UTF-8" agileek/plantuml:1.2022.3 > dai-flow-module-labo.svg
rai-flow:
	cat rai-flow.puml | docker run --rm -i -e JAVA_TOOL_OPTIONS="-Dfile.encoding=UTF-8" agileek/plantuml:1.2022.3 > rai-flow.svg
rai-flow-module-labo:
	cat rai-flow-module-labo.puml | docker run --rm -i -e JAVA_TOOL_OPTIONS="-Dfile.encoding=UTF-8" agileek/plantuml:1.2022.3 > rai-flow-module-labo.svg