name: Release
on:
  push:
    branches:
      - prod
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: 'npm'
      - name: Install
        run: npm ci --workspaces=false
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          MATTERMOST_WEBHOOK: ${{ secrets.MATTERMOST_WEBHOOK }}
        run: npx semantic-release