export const maskingExceptions: Record<string, string[]> = {
  analysis: ['created_by', 'id', 'sample_id', 'status'],
  analysis_dai: ['analysis_id', 'sent_method', 'state'],
  analysis_dai_documents: ['document_id'],
  analysis_errors: ['analysis_id'],
  analysis_rai: ['analysis_id', 'laboratory_id', 'source', 'state'],
  analysis_rai_documents: ['document_id'],
  analysis_report_documents: ['analysis_id', 'document_id'],
  analysis_residues: [
    'analysis_date',
    'analysis_id',
    'analysis_kind',
    'analysis_method',
    'compliance',
    'contamination_sources',
    'other_compliance',
    'pollution_risk',
    'precise_method',
    'reference',
    'result_higher_than_arfd',
    'result_kind',
    'substance_approved',
    'substance_authorised'
  ],
  companies: ['kinds', 'naf_code'],
  departments: ['geometry', 'id'],
  document_programming_plans: ['document_id', 'programming_plan_id'],
  documents: ['created_by', 'id', 'kind'],
  knex_migrations: ['name'],
  laboratories: [
    'address',
    'billing_address',
    'billing_city',
    'billing_postal_code',
    'city',
    'id',
    'name',
    'postal_code',
    'programming_plan_ids',
    'sacha_communication_method',
    'sacha_sigle',
    'short_name'
  ],
  laboratory_agreement_checks: ['checked_by', 'substance_kind'],
  laboratory_agreements: ['laboratory_id', 'substance_kind'],
  laboratory_analytical_competences: [
    'analysis_method',
    'analyte_reference',
    'analytical_competence',
    'analytical_method',
    'is_complete_definition_analysis',
    'residue_reference',
    'validation_method'
  ],
  laboratory_residue_mappings: ['label', 'laboratory_id', 'ssd2_id'],
  local_prescription_changes: [
    'department',
    'echelon',
    'kind',
    'region',
    'substance_kinds_laboratories'
  ],
  local_prescription_comments: [
    'created_by',
    'department',
    'id',
    'prescription_id',
    'region'
  ],
  local_prescription_substance_kinds_laboratories: [
    'department',
    'region',
    'substance_kind'
  ],
  local_prescriptions: [
    'department',
    'laboratory_id',
    'prescription_id',
    'region'
  ],
  notices: ['description', 'title', 'type'],
  notifications: ['category', 'kind'],
  prescription_changes: ['kind'],
  prescription_substances: ['analysis_method', 'prescription_id', 'substance'],
  prescriptions: ['id'],
  programming_plan_domains: ['label'],
  programming_plan_fields: ['programming_plan_id'],
  programming_plan_local_status: [
    'department',
    'programming_plan_id',
    'region',
    'status'
  ],
  programming_plan_national_coordinators: ['programming_plan_id', 'user_id'],
  programming_plans: [
    'closed_by',
    'context',
    'contexts',
    'created_by',
    'distribution_kind',
    'id',
    'launched_by',
    'legal_contexts',
    'matrices',
    'samples',
    'stages',
    'substance_kinds',
    'title'
  ],
  programming_sub_plan_fields_raw: ['inheritance'],
  programming_sub_plans_raw: [
    'analysis_permission_role',
    'context',
    'matrices',
    'programming_plan_id',
    'samples',
    'stages',
    'sub_plan_number',
    'substance_kinds'
  ],
  residue_analytes: ['analysis_id', 'reference', 'result_kind'],
  sacha_commemoratif_values: ['commemoratif_sigle', 'libelle', 'sigle'],
  sacha_commemoratifs: ['libelle', 'sigle', 'type_donnee', 'unite'],
  sacha_conf: [
    'version_reference_prescripteur',
    'version_reference_standardisees'
  ],
  sacha_residue_mappings: ['label', 'ssd2_id'],
  sacha_sender: ['sacha_sigle'],
  sample_documents: ['document_id', 'sample_id'],
  sample_items: [
    'destruction_date',
    'invoicing_date',
    'laboratory_id',
    'paid_date',
    'quantity_unit',
    'receipt_date',
    'recipient_kind',
    'sample_id',
    'seal_id',
    'shipping_date',
    'substance_kinds',
    'support_document_id'
  ],
  sample_sequence_numbers: ['region'],
  sample_specific_data_values: ['id', 'sample_id'],
  samples: [
    'compliance',
    'context',
    'department',
    'id',
    'laboratory_id',
    'legal_context',
    'matrices',
    'mono_substances',
    'multi_substances',
    'prescription_id',
    'programming_plan_id',
    'reference',
    'region',
    'sampled_by',
    'sampled_date',
    'sampled_time',
    'step'
  ],
  spatial_ref_sys: ['auth_name', 'proj4text', 'srtext'],
  specific_data_field_options: [
    'field_key',
    'label',
    'sacha_commemoratif_value_sigle',
    'value'
  ],
  specific_data_fields: [
    'hint_text',
    'input_type',
    'key',
    'label',
    'sacha_commemoratif_sigle'
  ],
  user_companies: ['user_id'],
  users: ['department', 'id', 'laboratory_id', 'region', 'roles', 'stages']
};
